<?php
$this->css()->append('/jquery/colorpicker/css/colorpicker.css', 'js-jquery-colorpicker');
$this->js()->append('/jquery/colorpicker/colorpicker.js', 'js-jquery-colorpicker');
$this->js()->append('/ld/appearance.js', 'admin');
?>

<table class="appearance-colors-form">
    <tr>
        <th></th>
        <th></th>
        <th></th>
        <th><?php echo $this->translate('Background') ?></th>
        <th><?php echo $this->translate('Border') ?></th>
        <th><?php echo $this->translate('Title') ?></th>
        <th><?php echo $this->translate('Text') ?></th>
    </tr>
    <?php if (in_array('base', $this->colorSchemes)) : ?>
    <tr>
        <th><?php echo $this->translate('Base') ?></th>
        <th><label><input name="colors[base-default]" value="1" <?php
            if ($this->colors['base-default'] == 1) echo 'checked="checked"' ?> type="radio"/><?php
            echo $this->translate('Default') ?></label></th>
        <th><label><input name="colors[base-default]" value="0" <?php
            if ($this->colors['base-default'] == 0) echo 'checked="checked"' ?> type="radio"/><?php
            echo $this->translate('Custom') ?></label></th>
        <?php foreach (array('ld-colors-background', 'ld-colors-border', 'ld-colors-title', 'ld-colors-text') as $key) : ?>
        <td><input size="7" class="color" name="colors[<?php echo $key ?>]" id="<?php echo $key ?>"
            style="background:#<?php echo $this->colors[$key] ?>" type="text" value="<?php echo $this->colors[$key] ?>"/></td>
        <?php endforeach ?>
    </tr>
    <?php endif ?>
    <?php if (in_array('bars', $this->colorSchemes)) : ?>
    <tr>
        <th><?php echo $this->translate('Bars') ?></th>
        <th><label><input name="colors[bars-default]" value="1" <?php
            if ($this->colors['bars-default'] == 1) echo 'checked="checked"' ?> type="radio"/><?php
            echo $this->translate('Default') ?></label></th>
        <th><label><input name="colors[bars-default]" value="0" <?php
            if ($this->colors['bars-default'] == 0) echo 'checked="checked"' ?> type="radio"/><?php
            echo $this->translate('Custom') ?></label></th>
        <?php foreach (array('ld-colors-background-2', 'ld-colors-border-2', 'ld-colors-title-2', 'ld-colors-text-2') as $key) : ?>
        <td><input size="7" class="color" name="colors[<?php echo $key ?>]" id="<?php echo $key ?>"
            style="background:#<?php echo $this->colors[$key] ?>" type="text" value="<?php echo $this->colors[$key] ?>"/></td>
        <?php endforeach ?>
    </tr>
    <?php endif ?>
    <?php if (in_array('panels', $this->colorSchemes)) : ?>
    <tr>
        <th><?php echo $this->translate('Panels') ?></th>
        <th><label><input name="colors[panels-default]" value="1" <?php
            if ($this->colors['panels-default'] == 1) echo 'checked="checked"' ?> type="radio"/><?php
            echo $this->translate('Default') ?></label></th>
        <th><label><input name="colors[panels-default]" value="0" <?php
            if ($this->colors['panels-default'] == 0) echo 'checked="checked"' ?> type="radio"/><?php
            echo $this->translate('Custom') ?></label></th>
        <?php foreach (array('ld-colors-background-3', 'ld-colors-border-3', 'ld-colors-title-3', 'ld-colors-text-3') as $key) : ?>
        <td><input size="7" class="color" name="colors[<?php echo $key ?>]" id="<?php echo $key ?>"
            style="background:#<?php echo $this->colors[$key] ?>" type="text" value="<?php echo $this->colors[$key] ?>"/></td>
        <?php endforeach ?>
    </tr>
    <?php endif ?>
</table>