<?php
$this->js()->append('/codemirror/codemirror.js', 'js-codemirror');
?>

<textarea id="css-editor" class="css-editor-textarea" cols="100" rows="15" name="css"><?php
    if (!empty($this->css)) {
        echo $this->escape($this->css);
    } else {
        echo "/*\nEmpty for now\n*/\n\n\n";
    }
?></textarea>

<script type="text/javascript">
  var editor = CodeMirror.fromTextArea('css-editor', {
    width: "860px",
    height: "250px",
    path: "<?php echo $this->site->getUrl('js') ?>/codemirror/",
    parserfile: "parsecss.js",
    stylesheet: "<?php echo $this->site->getUrl('css') ?>/codemirror/csscolors.css",
    iframeClass: "css-editor-frame"
  });
</script>
