<div class="ld-merger ld-feed">

<?php if (Ld_Auth::isAuthenticated()) : ?>
<ul class="h6e-tabs">
    <li<?php if ($this->feedType == 'personal') echo ' class="active"' ?>>
        <a href="<?php echo $this->url(array('action' => 'personal'), 'merger-feed') ?>">Personal Feed</a></li>
    <li<?php if ($this->feedType != 'personal') echo ' class="active"' ?>>
        <a href="<?php echo $this->url(array('action' => 'public'), 'merger-feed') ?>">Public Feed</a></li>
</ul>
<?php endif ?>

<div class="h6e-main">

<div class="h6e-page-content h6e-block has-tab">

    <?php $n = 0; foreach ($this->entries as $entry) :  ?>

    <div class="hentry">

    <?php printf('<img src="%1$s" width="%2$s" height="%2$s" alt="" class="avatar"/>', $entry['avatarUrl'], 32); ?>

    <div class="entry-inner">

    <?php if ($entry['screenName'] && $entry['userUrl']) : ?>
        <a class="username" href="<?php echo $entry['userUrl'] ?>"><?php echo $entry['screenName'] ?></a>
    <?php else  : ?>
        <strong><?php echo $entry['screenName'] ?></strong>
    <?php endif ?>

    <?php if ($entry['type'] == 'link') : ?>
          <?php if (!empty($entry['screenName'])) : echo $entry['action']; endif ?>
          <?php if (!empty($entry['enclosure'])) : ?>
            <img class="enclosure" src="<?php echo $entry['enclosure']->url ?>"/>
          <?php endif ?>
        <h2 class="h6e-entry-title"><a href="<?php echo $entry['link'] ?>"><?php echo $entry['title'] ?></a></h2>
        <?php if (!empty($entry['content'])) : ?>
            <div class="h6e-post-content"><?php echo $entry['content'] ?></div>
        <?php endif ?>

    <?php elseif ($entry['type'] == 'status') : ?>
        <span class="h6e-entry-title"><?php echo $entry['content'] ?></span>

    <?php else : ?>

        <?php if (!empty($entry['screenName'])) : echo $entry['action']; endif ?>
        <?php if ($entry['title'] != $entry['content']) : ?>
            <h2 class="h6e-entry-title"><a href="<?php echo $entry['link'] ?>"><?php echo $entry['title'] ?></a></h2>
        <?php endif ?>
        <?php if (!empty($entry['content'])) : ?>
            <div class="h6e-post-content"><?php echo $entry['content'] ?></div>
        <?php endif ?>

    <?php endif ?>

    <?php $instance = $this->site->getInstance($entry['instance']);  ?>

    <div class="h6e-post-info ld-app-name <?php if ($instance) echo $instance->getPackageId() ?>" style="clear:both">
        <?php echo Ld_Ui::relativeTime($entry['timestamp']) ?>
        <?php if ($instance) : ?>
            via <a href="<?php echo $instance->getUrl() ?>"><?php echo $instance->getName() ?></a>
        <?php endif ?>
    </div>

    </div>

    </div>

    <?php $n++; if ($n > 50) break; endforeach ?>

</div>

</div>

<div class="h6e-sidebar">
    <div class="h6e-sidebar-inner">

        <h3>Applications</h3>

        <?php $this->instancesList() ?>

    </div>
</div>

</div>