<h2><?php echo $this->translate("News Feed"); ?></h2>

<div class="ld-merger ld-feed">

<?php if (Ld_Auth::isAuthenticated()) : ?>
    <ul class="h6e-tabs">
        <li<?php if ($this->feedType == 'personal') echo ' class="active"' ?>>
            <a href="<?php echo $this->url(array('action' => 'personal'), 'merger-feed') ?>"><?php
                echo $this->translate("Personal Feed");
        ?></a></li>
        <li<?php if ($this->feedType != 'personal') echo ' class="active"' ?>>
            <a href="<?php echo $this->url(array('action' => 'public'), 'merger-feed') ?>"><?php
                echo $this->translate("Public Feed");
        ?></a></li>
        <?php if ($this->canAdmin) : ?>
        <li class="more">
            <a href="<?php echo $this->url(array('controller' => 'settings', 'action' => 'index'), 'merger-settings') ?>"><?php
                echo $this->translate("Configure");
        ?></a></li>
        <?php endif ?>
    </ul>
<?php endif ?>

<div class="h6e-main">

<div class="h6e-block<?php if (Ld_Auth::isAuthenticated()) echo ' has-tab' ?>">

    <?php $this->notification() ?>

    <?php $n = 0; foreach ($this->entries as $entry) : ?>

    <div class="hentry">

    <?php printf('<img src="%1$s" width="%2$s" height="%2$s" alt="" class="avatar"/>', $entry['avatarUrl'], 32); ?>

    <div class="entry-inner">

    <?php if ($entry['screenName'] && $entry['userUrl']) : ?>
        <a class="username" href="<?php echo $entry['userUrl'] ?>"><?php echo $entry['screenName'] ?></a>
    <?php else  : ?>
        <strong><?php echo $entry['screenName'] ?></strong>
    <?php endif ?>

    <?php if ($entry['type'] == 'link') : ?>
          <?php if (!empty($entry['screenName'])) : echo $entry['action']; endif ?>
          <?php if (!empty($entry['enclosure'])) : ?>
            <img class="enclosure" src="<?php echo $entry['enclosure']->url ?>"/>
          <?php endif ?>
        <h2 class="h6e-entry-title"><a href="<?php echo $entry['link'] ?>"><?php echo $this->escape($entry['title']) ?></a></h2>
        <?php if (!empty($entry['content'])) : ?>
            <div class="h6e-post-content"><?php echo $entry['content'] ?></div>
        <?php endif ?>

    <?php elseif ($entry['type'] == 'status') : ?>
        <span class="h6e-entry-title"><?php echo $entry['content'] ?></span>

    <?php else : ?>

        <?php if (!empty($entry['screenName'])) : echo $entry['action']; endif ?>
        <?php if ($entry['title'] != $entry['content']) : ?>
            <h2 class="h6e-entry-title"><a href="<?php echo $entry['link'] ?>"><?php echo $this->escape($entry['title']) ?></a></h2>
        <?php endif ?>
        <?php if (!empty($entry['content'])) : ?>
            <div class="h6e-post-content"><?php echo $entry['content'] ?></div>
        <?php endif ?>

    <?php endif ?>

    <?php $instance = $this->site->getInstance($entry['instance']);  ?>

    <div class="h6e-post-info ld-app-name <?php if ($instance) echo $instance->getPackageId() ?>" style="clear:both">
        <?php echo Ld_Ui::relativeTime($entry['timestamp']) ?>
        <?php if ($instance) : ?>
            via <a href="<?php echo $instance->getUrl() ?>"><?php echo $instance->getName() ?></a>
        <?php endif ?>
    </div>

    </div>

    </div>

    <?php $n++; if ($n > 50) break; endforeach ?>

    <?php if ($n == 0) : ?>
        <p><?php echo $this->translate("This news feed is currently empty. Maybe installing some applications will help fill it.") ?></p>
    <?php endif ?>

</div>

</div>

<?php
$parameters = array('admin' => $this->admin, 'site' => $this->site);
echo $this->partial('partials/sidebar.phtml', $parameters);
?>

</div>

<script type="text/javascript">

<?php
$updateUrl = $this->url() . '?format=json';
$hashes = array();
for ($i = 0; $i < 3; $i ++) {
    if (isset($this->entries[$i])) $hashes[] = $this->entries[$i]['hash'];
}
$updateUrl .= '&hashes=' . urlencode(implode(';', $hashes));
?>

$(function() {

    var title = document.title;

    var msg_singular = "<?php echo $this->translate("1 new update") ?>";
    var msg_plural = "<?php echo $this->translate("%s new updates") ?>";

    function update() {
        $.ajax({
          url: "<?php echo $updateUrl ?>",
          dataType: 'json',
          success: function(updates) {
              var n = updates.length;
              if (n > 0) {
                  document.title = title + ' (' + n + ')';
                  var notice = $("#merger-notification");
                  if (notice.length == 0) {
                      notice = $('<div id="merger-notification" class="ld-notice"></div>').prependTo(".h6e-main .h6e-block");
                  }
                  var x = (n >= 50 ? '50+' : n);
                  var message = n == 1 ? msg_singular : msg_plural.replace('%s', x);
                  notice.html('<a href="<?php echo $this->url() ?>">' + message + '</a>');
              }
          }
        });
    }

    setInterval(update, (1000 * 60 / 2));

});

</script>
