<?php
echo $this->doctype('XHTML1_STRICT')->__tostring() . "\n" ?>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<?php echo $this->headTitle()->__tostring() . "\n" ?>
<?php echo '<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>' . "\n"  ?>
<?php echo $this->headLink()->__tostring() . "\n" ?>
<?php echo $this->headStyle()->__tostring() . "\n" ?>
<?php echo $this->headScript()->__tostring() . "\n" ?>
</head>
<body>

<div class="h6e-top-bar"><div class="h6e-top-bar-inner">
  <div class="a">
      <?php echo $this->navigation()->breadcrumbs(); ?>
  </div>
  <div class="b">
      <?php if ($this->authenticated && !empty($this->user)) : ?>
          Salut <?php echo $this->user['fullname'] ?>!
          -
          <a href="?ld_auth_action=logout">Log Out</a>
      <?php elseif (!$this->authenticated) : ?>
          <a class="h6e-login" href="<?php echo $this->url(array('module' => 'default', 'controller' => 'auth', 'action' => 'login')) ?>">Log In</a>
      <?php endif ?>
  </div>
</div></div>

<div class="h6e-main-content">

  <div class="h6e-page-content">
      <?php echo $this->layout()->content ?>
  </div>

  <div class="h6e-simple-footer">
      <p>This is <a href="http://ladistribution.net/">La Distribution</a></p>
  </div>

</div>

<?php Ld_Ui::super_bar(); ?>

</body>
</html>