<h2><?php echo $this->translate("Global settings") ?></h2>

<?php if (!empty($this->preferences)) : ?>

<form method="post" action="<?php echo $this->url() ?>">

    <?php
    $options = array('ns' => 'configuration', 'configuration' => $this->configuration, 'preferences' => $this->preferences);
    $this->preferencesRenderer()->setOptions($options)->renderTable();
    ?>

    <input type="submit" class="submit button" value="<?php echo $this->translate('Update') ?>"/>

</form>

<?php else : ?>

<p><?php echo $this->translate('No preference available.') ?></p>

<?php endif ?>