<h2><?php echo $this->translate("Settings") ?></h2>

<div class="ld-panel">

<?php $this->partialNavigationMenu('Settings') ?>

<div class="ld-panel-content h6e-block">

<h3><?php echo $this->translate("General Settings") ?></h3>

<?php if (!empty($this->preferences)) : ?>

<form method="post" action="<?php echo $this->url() ?>">

    <?php
    $options = array('ns' => 'configuration', 'configuration' => $this->configuration, 'preferences' => $this->preferences);
    $this->preferencesRenderer()->setOptions($options)->renderTable();
    ?>

    <?php if ($this->canManageLocales) : ?>
    <table class="ld-preferences">
        <tr>
            <th><label>Locales</label></th>
            <td>
    <?php foreach ($this->allLocales as $id => $label) : ?>
        <input type="checkbox" id="locale-<?php echo $id ?>" name="locales[<?php echo $id ?>]"
            <?php if (isset($this->locales[$id])) : ?> checked="checked"<?php endif ?> />
        <label for="locale-<?php echo $id ?>"><?php echo $this->escape($label) ?></label>
    <?php endforeach ?>
            </td>
        </tr>
    </table>
    <?php endif ?>

    <input type="submit" class="submit button" value="<?php echo $this->translate('Update') ?>"/>

</form>

<?php else : ?>

<p><?php echo $this->translate('No preference available.') ?></p>

<?php endif ?>

</div>

</div>