<h2>Repositories</h2>

<?php echo $this->partial('repositories/list.phtml', array('repositories' => $this->repositories)); ?>

<h3>Also:</h3>

<ul>
    <li><a href="<?php echo $this->url(array('controller' => 'repositories', 'action' => 'new'), 'default') ?>?type=local">
        Create a local repository
    </a></li>
    <li><a href="<?php echo $this->url(array('controller' => 'repositories', 'action' => 'new'), 'default') ?>?type=remote">
        Add a remote repository
    </a></li>
</ul>
