<?php if (empty($this->repositories) || count($this->repositories) == 0) : ?>
    
    <p>None</p>
    
<?php else : ?>

    <ul>
    <?php
    foreach ($this->repositories as $id => $repository) {
        $url = $this->url(array('controller' => 'repositories', 'id' => $id, 'action' => 'manage'), 'default');
        printf("<li><a href=\"%s\">%s</a></li>\n", $url, $repository->name);
    }
    ?>
    </ul>

<?php endif ?>