<?php if (empty($this->applications) &&  empty($this->libraries) && empty($this->extensions)) : ?>

    <p>This repository is empty</p>

<?php else : ?>

<?php $this->headScript()->offsetSetFile('ld-data', Zend_Registry::get('site')->getUrl('js') . '/ld/ld-data.js'); ?>

<table class="h6e-data">
    <?php foreach(array('applications', 'libraries', 'extensions') as $type) : ?>
        <?php if (!empty($this->$type)) : ?>
            <tr>
                <th colspan="3"><strong><?php echo ucfirst($type) ?></strong></th>
            </tr>
            <tr class="th2">
                <th>name</th>
                <th>package</th>
                <th>version</th>
            </tr>
            <tbody>
            <?php foreach ($this->$type as $package) : ?>
                <tr>
                    <td><?php echo $package->name ?></td>
                    <td><?php echo $package->id ?></td>
                    <td><?php echo $package->version ?></td>
                </tr>
            <?php endforeach ?>
            </tbody>
        <?php endif ?>
    <?php endforeach ?>
</table>

<?php endif ?>