<h2><?php echo $this->translate("Settings") ?></h2>

<div class="ld-panel">

<?php $this->partialNavigationMenu('Settings') ?>

<div class="ld-panel-content h6e-block">

<h3><?php echo $this->translate("Delete a connection") ?></h3>

<?php if ($this->used) : ?>

<p><?php echo $this->translate("You can't delete this connection. It's currently used by at least one application.") ?></p>

<?php else : ?>

<p><?php echo $this->translate("Are you sure you want to delete this database connection?") ?></p>

<form method="post" action="">

    <input type="hidden" name="id" value="<?php echo $this->escape($this->id) ?>"/>
    <input type="submit" class="submit button ld-button" value="<?php echo $this->translate("Delete") ?>"/>

</form>

<?php endif ?>

</div>

</div>