<h2><?php echo $this->translate("Databases connections") ?></h2>

<?php if (empty($this->databases) || count($this->databases) == 0) : ?>

    <p><?php echo $this->translate("None|database") ?></p>

<?php else : ?>

    <table class="h6e-data">

    <tr>
       <th><?php echo $this->translate("Type") ?></th>
       <th><?php echo $this->translate("Host") ?></th>
       <th><?php echo $this->translate("Name") ?></th>
       <th colspan="2"><?php echo $this->translate("Actions") ?></th>
    </tr>

    <tbody>

    <?php foreach ($this->databases as $id => $database) : ?>

        <tr>
            <td><?php echo $this->escape($database['type']) ?></td>
            <td><?php echo $this->escape($database['host']) ?></td>
            <td><?php echo $this->escape($database['name']) ?></td>
            <td>
                <a href="<?php echo $this->url(array('action' => 'edit', 'id' => $id )); ?>"><?php
                    echo $this->translate("edit");
                ?></a>
            </td>
            <td>
                <a href="<?php echo $this->url(array('action' => 'delete', 'id' => $id )); ?>"><?php
                    echo $this->translate("delete");
                ?></a>
            </td>
        </tr>

    <?php endforeach ?>

    </tbody>

    </table>

<?php endif ?>

<h3><?php echo $this->translate("You can:") ?></h3>

<ul>
    <li><a href="<?php echo $this->url(array('action' => 'new')); ?>"><?php
        echo $this->translate("Add a database connection");
    ?></a></li>
</ul>
