<h2><?php echo $this->translate("Settings") ?></h2>

<div class="ld-panel">

<?php $this->partialNavigationMenu('Settings') ?>

<div class="ld-panel-content h6e-block">

<h3><?php echo $this->translate("Databases") ?></h3>

<?php if (empty($this->databases) || count($this->databases) == 0) : ?>

    <p><?php echo $this->translate("No database connection registered.") ?></p>

<?php else : ?>

    <table class="h6e-data">

    <tr>
       <th><?php echo $this->translate("Type") ?></th>
       <th><?php echo $this->translate("Host") ?></th>
       <th><?php echo $this->translate("Name") ?></th>
       <th><?php echo $this->translate("Usage") ?></th>
       <th><?php echo $this->translate("Status") ?></th>
       <th colspan="2"><?php echo $this->translate("Actions") ?></th>
    </tr>

    <tbody>

    <?php foreach ($this->databases as $id => $database) : ?>
        <?php if ($database['type'] == 'mysql-master') { $master = $database; $master['id'] = $id; continue; } ?>
        <?php $used = $this->site->isDatabaseUsed($id); ?>
        <?php $test = $this->site->testDatabase($database, false); ?>
        <tr>
            <td><?php echo $this->escape($database['type']) ?></td>
            <td><?php echo $this->escape($database['host']) ?></td>
            <td><?php echo $this->escape($database['name']) ?></td>
            <td><?php echo $used ? sprintf($this->translate('used by %1$d applications'), $used) :  $this->translate('unused') ?></td>
            <?php if ($test) : ?>
                <td class="ok"><?php // echo $this->translate('ok') ?></td>
            <?php else : ?>
                <td class="error"><?php // echo $this->translate('unavailable') ?></td>
            <?php endif ?>
            <td>
                <a href="<?php echo $this->url(array('action' => 'edit', 'id' => $id )); ?>"><?php
                    echo $this->translate("edit");
                ?></a>
            </td>
            <td>
                <a href="<?php echo $this->url(array('action' => 'delete', 'id' => $id )); ?>"><?php
                    echo $this->translate("delete");
                ?></a>
            </td>
        </tr>

    <?php endforeach ?>

    </tbody>

    </table>

<?php endif ?>

<h3><?php echo $this->translate("You can:") ?></h3>

<ul>
    <li><a href="<?php echo $this->url(array('action' => 'new')); ?>"><?php
        echo $this->translate("Register an existing database");
    ?></a></li>
    <?php if (isset($master)) : ?>
        <li><a href="<?php echo $this->url(array('action' => 'create', 'master' => $master['id'])); ?>"><?php
            echo $this->translate("Create a new database");
        ?></a></li>
    <?php elseif (defined('LD_DB_MASTER') && constant('LD_DB_MASTER')) : ?>
        <li><a href="<?php echo $this->url(array('action' => 'master')); ?>"><?php
            echo $this->translate("Register master credentials");
        ?></a></li>
    <?php endif ?>
</ul>

</div>

</div>
