<?php if (!$this->site->isChild() && empty($this->roles)) : ?>

    <h2><?php echo $this->translate("Installation") ?></h2>

    <p><?php echo $this->translate(
        "There is no user registered yet. Registering a first user is necessary to password protect this admin and install others applications."
    ) ?></p>

    <p><a href="<?php echo $this->url(array('module' => 'default', 'controller' => 'auth', 'action' => 'register')) ?>"><?php
        echo $this->translate("Register the first user now.") ?></a></p>

<?php return; endif ?>

<h2><?php echo $this->translate("Applications") ?></h2>

<?php $this->instancesList() ?>

<?php if (!$this->site->isChild() && defined('LD_MULTI_SITES') && constant('LD_MULTI_SITES')) : ?>
    
<h2><?php echo $this->translate("Sub Sites") ?></h2>

<div class="ld-instance-list">
    
    <ul class="blocks mini is-admin">
        <?php foreach ($this->site->getSites() as $id => $config) : $subsite = new Ld_Site_Child($config); $subsite->setParentSite($this->site); ?>
        <li class="">
            <div class="name">
                → <a href="<?php echo $subsite->getUrl() ?>"><?php echo $subsite->getName() ?></a><br/>
            </div>
            <?php if ($this->userRole == 'admin') :?>
            <div class="links">
                <?php $manageUrl = $this->url(array('controller' => 'sites', 'action' => 'edit', 'id' => $id)); ?>
                <?php printf('<a class="view" href="%s">%s</a>', $manageUrl, $this->translate("Settings")); ?>
            </div>
            <?php endif ?>
        </li>
        <?php endforeach ?>
        <?php if ($this->canManageSites) : ?>
            <li class="empty new">
                <a href="/ld-mu/slotter/sites/new">Ajouter un nouveau site</a>
            </li>
        <?php endif ?>
    </ul>
<div>

<?php endif ?>

<?php if ($this->canAdmin) : ?>

<div class="ld-home">

    <div class="manage">
        <h2><?php echo $this->translate->translate("Manage") ?></h2>
        <?php
        $pages = array();
        $pages[] = array('controller' => 'users', 'label' => "Users");
        if ($this->canManageRepositories || $this->canManageDatabases) {
            $pages[] = array('controller' => 'repositories', 'label' => "Ressources");
        }
        // if ($this->canManageDatabases) {
        //     $pages[] = array('controller' => 'databases', 'label' => "Databases");
        // }
        // if ($this->canManageLocales) {
        //     $pages[] = array('controller' => 'locales', 'label' => "Locales");
        // }
        // if ($this->canManagePlugins) {
        //     $pages[] = array('controller' => 'plugins', 'label' => "Plugins");
        // }
        $pages[] = array('controller' => 'settings', 'label' => "Settings");
        ?>
        <ul>
            <?php foreach ($pages as $page) :
                $label = $this->translate($page['label']);
                $url = $this->url(array('controller' => $page['controller'], 'action' => 'index'));
            ?>
            <li><a href="<?php echo $url ?>"><?php echo $label ?></a></li>
            <?php endforeach ?>
        </ul>
    </div>
    
    <?php if ($this->canUpdate) : ?>
    <div class="update">
        <h2><?php echo $this->translate("Updates") ?></h2>
        <?php if ($this->canAdmin && $this->hasUpdate) :
            $updateUrl = $this->url(array('controller' => 'index', 'action' => 'update'), 'update');
            $updateString = $this->translate(
                "There is some updates available. It's recommended to <a href=\"%s\">upgrade now.</a>");
            ?>
            <p><?php printf($updateString, $updateUrl); ?></p>
        <?php else: ?>
            <p><?php echo $this->translate("Everything fine, nothing to update.") ?></p>
        <?php endif ?>
    </div>
    <?php endif ?>

</div>

<?php if (empty($this->databases) || count($this->databases) == 0) : ?>

    <?php $newDbUrl = $this->url(array('controller' => 'databases', 'action' => 'new')); ?>

    <p><strong><?php echo $this->translate("Notice:") ?></strong>
    <?php echo $this->translate("There is no database connection registered yet. A database is often needed to install new applications.") ?>
    <!--
    <a href="<?php echo $newDbUrl ?>"><?php echo $this->translate("Add a database connection") ?></a>
    -->
    </p>

<?php endif ?>

<?php endif ?>
