<?php if (empty($this->roles)) : ?>

    <h2><?php echo $this->translate("Installation") ?></h2>

    <p><?php echo $this->translate(
        "There is no user registered yet. Registering a first user is necessary to password protect this admin and install others applications."
    ) ?></p>

    <p><a href="<?php echo $this->url(array('controller' => 'users', 'action' => 'new')) ?>"><?php
        echo $this->translate("Register the first user now.") ?></a></p>

<?php return; endif ?>

<h2><?php echo $this->translate("Applications") ?></h2>

<?php $this->instancesList() ?>

<?php if ($this->canAdmin) : ?>

<div class="ld-home">

    <div class="manage">
        <h2><?php echo $this->translate->translate("Manage") ?></h2>
        <?php
        $pages = array();
        $pages[] = array('controller' => 'users', 'label' => "Users");
        if ($this->canManageRepositories) {
            $pages[] = array('controller' => 'repositories', 'label' => "Repositories");
        }
        if ($this->canManageDatabases) {
            $pages[] = array('controller' => 'databases', 'label' => "Databases");
        }
        $pages[] = array('controller' => 'locales', 'label' => "Locales");
        if ($this->canManagePlugins) {
            $pages[] = array('controller' => 'plugins', 'label' => "Plugins");
        }
        $pages[] = array('controller' => 'settings', 'label' => "Global settings");
        ?>
        <ul>
            <?php foreach ($pages as $page) :
                $label = $this->translate($page['label']);
                $url = $this->url(array('controller' => $page['controller'], 'action' => 'index'));
            ?>
            <li><a href="<?php echo $url ?>"><?php echo $label ?></a></li>
            <?php endforeach ?>
        </ul>
    </div>

    <div class="update">
        <h2><?php echo $this->translate("Updates") ?></h2>
        <?php if ($this->canAdmin && $this->hasUpdate) :
            $updateUrl = $this->url(array('controller' => 'index', 'action' => 'update'), 'update');
            $updateString = $this->translate(
                "There is some updates available. It's recommended to <a href=\"%s\">upgrade now.</a>");
            ?>
            <p><?php printf($updateString, $updateUrl); ?></p>
        <?php else: ?>
            <p><?php echo $this->translate("Everything fine, nothing to update.") ?></p>
        <?php endif ?>
    </div>

</div>

<?php if (empty($this->databases) || count($this->databases) == 0) : ?>

    <?php $newDbUrl = $this->url(array('controller' => 'databases', 'action' => 'new')); ?>

    <p><strong><?php echo $this->translate("Notice:") ?></strong>
    <?php echo $this->translate("There is no database connection registered yet. A database is often needed to install new applications.") ?>
    <!--
    <a href="<?php echo $newDbUrl ?>"><?php echo $this->translate("Add a database connection") ?></a>
    -->
    </p>

<?php endif ?>

<?php endif ?>
