<?php if (!$this->site->isChild() && empty($this->roles)) : ?>

    <h2><?php echo $this->translate("Installation") ?></h2>

    <p><?php echo $this->translate(
        "There is no user registered yet. Registering a first user is necessary to password protect this admin and install others applications."
    ) ?></p>

    <p><a href="<?php echo $this->url(array('module' => 'default', 'controller' => 'auth', 'action' => 'register')) ?>"><?php
        echo $this->translate("Register the first user now.") ?></a></p>

<?php return; endif ?>

<?php if ($this->canAdmin) : ?>
<ul class="ld-nav">
    <li><a href="<?php echo $this->url(array('module' => 'slotter', 'controller' => 'settings')) ?>"><?php echo $this->translate("Settings") ?></a></li>
</ul>
<?php endif ?>

<h2><?php echo $this->translate("Applications") ?></h2>

<?php $this->instancesList() ?>

<?php if (!$this->site->isChild() && defined('LD_MULTI_SITES') && constant('LD_MULTI_SITES')) : ?>

<h2><?php echo $this->translate("Sites") ?></h2>

<div class="ld-instance-list">

    <ul class="blocks mini is-admin instance-list">
        <?php foreach ($this->site->getSites() as $id => $config) : $subsite = new Ld_Site_Child($config); $subsite->setParentSite($this->site); ?>
        <li class="">
            <div class="name">
                <a href="<?php echo $subsite->getUrl() ?>"><?php echo $subsite->getName() ?></a><br/>
            </div>
            <?php if ($this->userRole == 'admin') :?>
                <?php $manageUrl = $this->url(array('controller' => 'sites', 'action' => 'edit', 'id' => $id)); ?>
                <?php printf('<a class="settings" href="%s">%s</a>', $manageUrl, $this->translate("Settings")); ?>
            <?php endif ?>
        </li>
        <?php endforeach ?>
        <?php if ($this->canManageSites) : ?>
            <li class="empty new">
                <?php $newSiteUrl = $this->url(array('controller' => 'sites', 'action' => 'new')); ?>
                <a href="<?php echo $newSiteUrl ?>"><?php echo $this->translate("Create a new site") ?></a>
            </li>
        <?php endif ?>
    </ul>
<div>

<?php endif ?>

<?php if ($this->canAdmin) : ?>

<div class="ld-home">

    <?php if ($this->hasUpdate) : ?>
    <div class="update">
        <h2><?php echo $this->translate("Updates") ?></h2>
        <?php
        $updateUrl = $this->url(array('controller' => 'index', 'action' => 'update'), 'update');
        $updateString = $this->translate(
            "There is some updates available. It's recommended to <a href=\"%s\">upgrade now.</a>");
        ?>
        <p><?php printf($updateString, $updateUrl); ?></p>
    </div>
    <?php endif ?>

</div>

<?php if (empty($this->databases) || count($this->databases) == 0) : ?>

    <?php $newDbUrl = $this->url(array('controller' => 'databases', 'action' => 'new')); ?>

    <p><strong><?php echo $this->translate("Notice:") ?></strong>
    <?php echo $this->translate("There is no database registered yet. A database is often needed to install new applications.") ?>
    <a href="<?php echo $newDbUrl ?>"><?php echo $this->translate("Register a database.") ?></a>
    </p>

<?php endif ?>

<?php endif ?>
