<?php if ($this->update) : ?>
    <?php
    // handle an issue when upgrading frrom barbes to a newer version
    header("Location:" . $this->url(array('controller' => 'index', 'action' => 'update'), 'update'));
    exit;
    ?>
<?php endif ?>

<h2><?php echo $this->translate('Update') ?></h2>

<?php if (empty($this->libraries) && empty($this->applications)) : ?>

    <p><?php echo $this->translate('Everything is up to date.') ?></p>

<?php else : ?>

<form action="" method="post">

<table class="h6e-data">
    <?php if (!empty($this->libraries)) : ?>
        <tr>
            <th colspan="6"><strong><?php echo $this->translate('Libraries') ?></strong></td>
        </tr>
        <tr class="th2">
            <th></th>
            <th colspan="3"><?php echo $this->translate('package') ?></th>
            <th><?php echo $this->translate('current version') ?></th>
            <th><?php echo $this->translate('new version') ?></th>
        </tr>

        <?php foreach ($this->libraries as $library) : ?>
            <tr>
                <td><input type="checkbox" checked="checked" name="libraries[<?php echo $library->getPackageId() ?>]" /></td>
                <td colspan="3"><?php echo $library->getPackageId() ?></td>
                <td><?php echo $library->getVersion() ?></td>
                <td><?php echo $library->hasUpdate ? $library->hasUpdate :
                    '<em>' . $this->translate('none') . '</em>' ?></td>
            </tr>
        <?php endforeach ?>
    <?php endif ?>
    <?php if (!empty($this->applications)) : ?>
        <tr>
            <th colspan="6"><strong><?php echo $this->translate('Applications') ?></strong></td>
        </tr>
        <tr class="th2">
            <th></th>
            <th><?php echo $this->translate('name') ?></th>
            <th><?php echo $this->translate('path') ?></th>
            <th><?php echo $this->translate('package') ?></th>
            <th><?php echo $this->translate('current version') ?></th>
            <th><?php echo $this->translate('new version') ?></th>
        </tr>
        <?php foreach ($this->applications as $id => $application) : ?>
            <tr>
                <td>
                    <?php // if ($application->hasUpdate && $application->hasUpdate !== true) : ?>
                        <input type="checkbox" checked="checked" name="applications[<?php echo $id ?>]" />
                    <?php // endif ?>
                </td>
                <td><?php echo $application->getName() ?></td>
                <td><?php echo $application->getPath() ?></td>
                <td><?php echo $application->getPackageId() ?></td>
                <td><?php echo $application->getVersion() ?></td>
                <td><?php echo $application->hasUpdate && $application->hasUpdate !== true ?
                    $application->hasUpdate : '<em>' . $this->translate('none') . '</em>' ?></td>
            </tr>
            <?php foreach ($application->getExtensions() as $extension) : ?>
                <?php if (($extension->hasUpdate = $extension->hasUpdate()) || $this->all) : ?>
                    <tr>
                        <td><input type="checkbox" checked="checked"
                            name="extensions[<?php echo $id ?>][<?php echo $extension->getPackageId() ?>]" /></td>
                        <td colspan="2">&nbsp;</td>
                        <td><?php echo $extension->getPackageId() ?></td>
                        <td><?php echo $extension->getVersion() ?></td>
                        <td><?php echo $extension->hasUpdate ?
                            $extension->hasUpdate : '<em>' . $this->translate('none') . '</em>' ?></td>
                    </tr>
                <?php endif ?>
            <?php endforeach ?>
        <?php endforeach ?>
    <?php endif ?>
</table>

<input type="submit" class="submit button" value="<?php echo $this->translate('Update selected') ?>"/>

</form>

<?php endif ?>
