<?php $this->instanceNavigation() ?>

<h2>Backups</h2>

<h3>Existing</h3>

<?php if (empty($this->backups) || count($this->backups) == 0) : ?>

    <p>None available</p>

<?php else : ?>

    <?php $this->headScript()->offsetSetFile('ld-data', Zend_Registry::get('site')->getUrl('js') . '/ld/ld-data.js'); ?>

    <table class="h6e-data">
        <tr class="th1">
            <th>File</th>
            <th>Size</th>
            <th colspan="3">Actions</th>
        </tr>
    <?php
    foreach ($this->backups as $backup) {
        $downloadUrl = $this->instanceActionUrl('backups') . '?download=' . $backup['filename'];
        $restoreUrl = $this->instanceActionUrl('backups') . '?restore=' .   $backup['filename'];
        $deleteUrl = $this->instanceActionUrl('backups') . '?delete=' .   $backup['filename'];
        ?>
        <tr>
            <td><?php echo $backup['filename'] ?></td>
            <td><?php echo $backup['size'] ?></td>
            <td><a href="<?php echo $downloadUrl ?>">Download</a></td>
            <td><a href="<?php echo $restoreUrl ?>">Restore</a></td>
            <td><a href="<?php echo $deleteUrl ?>">Delete</a></td>
        </tr>
        <?php
    }
    ?>
    </table>

<?php endif ?>

<h3>New</h3>

<form action="" method="post">
    <input type="hidden" name="dobackup" value="now" />
    <input type="submit" value="Make a backup now" />
</form>

<br />

<h3>Upload</h3>

<form action="" method="post" enctype="multipart/form-data">
    <input type="file" name="archive" />
    <input name="upload" type="submit" class="submit" value="Upload" />
</form>
