<?php $this->instanceNavigation() ?>

<h2 class="h6e-entry-title">Configure</h2>

<?php if (!empty($this->preferences)) : ?>

<form method="post" action="">
    
    <input type="hidden" name="id" value="<?php echo $this->escape($this->instance->id) ?>"/>
    
    <?php $this->preferencesRenderer($this->preferences, $this->configuration, 'configuration'); ?>
    
    <input type="submit" class="submit button" value="Update"/>

</form>

<?php else : ?>

<p>No preferences available for this application.</p>

<?php endif ?>