<?php $this->instanceNavigation() ?>

<h2 class="h6e-entry-title">Manage</h2>

<h3>Overview</h3>

<table class="h6e-data">
    <tr>
        <th>package</th>
        <th>type</th>
        <th>version</th>
        <th>status</th>
        <th>action</th>
    </tr>
    <tr>
        <td><?php echo $this->instance->getPackageId() ?></td>
        <td><?php echo $this->instance->getType() ?></td>
        <td><?php echo $this->instance->getVersion() ?></td>
        <td><?php echo ($this->instance->hasUpdate = $this->instance->hasUpdate()) ? 'Need update' : 'Up to date' ?></td>
        <td>
        <?php if ($this->instance->hasUpdate) : ?>
            <a href="<?php echo $this->instanceActionUrl('update') ?>?version=<?php echo $this->instance->hasUpdate ?>">update</a>
        <?php endif ?>
        </td>
    </tr>
    <?php // $extensions = $this->instance->getExtensions() ?>
    <?php if (count($this->extensions) > 0) : ?>
        <tr><td colspan="5"><em>Extensions</em></td></tr>
        <?php foreach($this->extensions as $extension) : ?>
            <tr>
                <td><?php echo $extension->getPackageId() ?></td>
                <td><?php echo $extension->getType() ?></td>
                <td><?php echo $extension->getVersion() ?></td>
                <td><?php echo $extension->hasUpdate ? 'Need update' : 'Up to date' ?></td>
                <td>
                    <?php if ($extension->hasUpdate) : ?>
                        <a href="<?php echo $this->instanceActionUrl('extensions') . '?update=' . $extension->getPath() ?>">update</a>
                    <?php endif ?>
                    <a href="<?php echo $this->instanceActionUrl('extensions') . '?remove=' . $extension->getPath() ?>">remove</a>
                </td>
            </tr>
        <?php endforeach ?>
    <?php endif ?>
</table>

<p>You can also:</p>

<ul>
    <li><a href="<?php echo $this->instanceActionUrl('delete') ?>">Delete this application</a></li>
</ul>
