<?php if (isset($this->archive)) : ?>

    <p>You should not see this for now.</p>

<?php else : ?>

    <h2>Restore an archive</h2>
    
    <?php if (empty($this->archives) || count($this->archives) == 0) : ?>
        <p>None available</p>
    <?php else : ?>
        <ul>
        <?php
        foreach ($this->archives as $filename) {
            $url = $this->instanceActionUrl('restore') . '?archive=' .  $filename;
            printf("<li><a href=\"%s\">%s</a></li>", $url, $filename);
        }
        ?>
        </ul>
    <?php endif ?>

<?php endif ?>