<?php $this->instanceNavigation() ?>

<h2 class="h6e-entry-title">Themes</h2>

<h3>Available Themes</h3>

<form method="post" action="">

    <input type="hidden" name="id" value="<?php echo $this->escape($this->instance->id) ?>"/>

    <?php if (!empty($this->themes)) : ?>

        <div class="themes">

            <?php foreach($this->themes as $id => $theme) : ?>

                <?php $screenshot = isset($theme['screenshot']) ?
                    $theme['screenshot'] : 'http://h6e.net/releases/wp-minimal-screenshot.png' ?>

                <div class="theme">
                <label for="theme-<?php echo $id ?>">
                <img src="<?php echo $screenshot ?>" width="240" height="180" alt="" />
                <input id="theme-<?php echo $id ?>" <?php echo ($theme['active'] ? 'checked="checked"' : '') ?>
                    type="radio" name="theme" value="<?php echo $id ?>" />
                <?php echo $theme['name'] ?>
                </label>
                </div>

            <?php endforeach ?>

        </div>

        <div style="margin:1em 0">
        <input type="submit" class="submit button" value="Update"/>
        </div>

    <?php else: ?>

        <p>No theme available for this application.</p>

    <?php endif ?>

</form>

<?php if (!empty($this->preferences)) : ?>

    <h3>Theme Preferences</h3>

    <form method="post" action="">

        <input type="hidden" name="id" value="<?php echo $this->escape($this->instance->id) ?>"/>

        <?php $this->preferencesRenderer($this->preferences, $this->configuration, 'configuration'); ?>

        <div style="margin-bottom:2em">
        <input type="submit" class="submit button" value="Update"/>
        </div>

    </form>

<?php endif ?>

<h3>Install More Themes</h3>

<?php
if (isset($this->extensions) && count($this->extensions) > 0) {
    echo '<ul>';
    foreach ($this->extensions as $id => $extension) {
        $url = $this->instanceActionUrl('extensions') . '?add=' . $extension->id;
        printf("<li><a href=\"%s\">%s</a></li>", $url, $extension->name);
    }
    echo '</ul>';
} else {
    echo '<p>No more theme are available for this application.</p>';
}
?>
