<?php
$this->headLink()->appendStylesheet(LD_CSS_URL . '/h6e-minimal/h6e-minimal.css', 'screen');
$this->headLink()->appendStylesheet(LD_ADMIN_URL . '/css/default.css', 'screen');
echo $this->doctype('XHTML1_STRICT')->__tostring() . "\n" ?>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<?php echo $this->headTitle()->__tostring() . "\n" ?>
<?php echo '<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>' . "\n"  ?>
<?php echo $this->headLink()->__tostring() . "\n" ?>
<?php echo $this->headStyle()->__tostring() . "\n" ?>
<?php echo $this->headScript()->__tostring() . "\n" ?>
</head>
<body>

<div class="user-info">
    <?php if (isset($_SERVER['REMOTE_USER'])) : ?>
        you are <strong><?php echo $_SERVER['REMOTE_USER'] ?></strong>
    <?php endif ?>
    &nbsp;
</div>

<div class="h6e-main-content">

  <h1 class="h6e-page-title"><a href="<?php echo LD_ADMIN_URL ?>"><?php echo $this->title ?></a></h1>

  <div class="h6e-page-content">
      <?php echo $this->layout()->content ?>
  </div>

  <div class="h6e-simple-footer">
      <p>Powered by <a href="http://h6e.net/">h6e.net</a></p>
  </div>

</div>

</body>
</html>