<ul class="ld-nav">
    <li><a href="<?php echo $this->url(array('module' => 'merger', 'controller' => 'index', 'action' => 'index'), 'default') ?>"><?php echo $this->translate("Back to News Feed") ?></a></li>
</ul>

<h2><?php echo $this->translate("News Feed") ?></h2>

<div class="ld-panel">

<div class="ld-panel-content h6e-block no-tab">

<h3><?php echo $this->translate("Settings") ?></h3>

<form method="post" action="">

<table class="h6e-data">
    <tr>
        <th></th>
        <th style="width:100px;text-align:center"><?php echo $this->translate("Personal Feed") ?></th>
        <th style="width:100px;text-align:center"><?php echo $this->translate("Public Feed") ?></th>
    </tr>
    <?php foreach ($this->applications as $id => $feeds) : ?>
        <?php $instance = $this->site->getInstance($id); ?>
        <tr class="th2">
            <th><?php echo $instance->getName() ?></th>
            <td></td>
            <td></td>
        </tr>
        <?php foreach ($feeds as $feed) : $feedId = $feed['id']; ?>
            <tr>
                <td><?php echo $feed['title'] ?></td>
                <td style="text-align:center">
                    <?php if ($feed['rel'] != 'public-feed') : ?>
                        <?php $checked = !isset($this->config['personal'][$id][$feedId]) || $this->config['personal'][$id][$feedId] == 1;  ?>
                        <input name="<?php echo "personal[$id][$feedId]" ?>" type="hidden" value="0"/>
                        <input name="<?php echo "personal[$id][$feedId]" ?>" type="checkbox" <?php if ($checked) echo 'checked="checked"' ?> value="1"/>
                    <?php endif ?>
                </td>
                <td style="text-align:center">
                    <?php if ($feed['rel'] != 'personal-feed') : ?>
                        <?php $checked = !isset($this->config['public'][$id][$feedId]) || $this->config['public'][$id][$feedId] == 1;  ?>
                        <input name="<?php echo "public[$id][$feedId]" ?>" type="hidden" value="0"/>
                        <input name="<?php echo "public[$id][$feedId]" ?>" type="checkbox" <?php if ($checked) echo 'checked="checked"' ?> value="1"/>
                    <?php endif ?>
                </td>
            </tr>
        <?php endforeach ?>
    <?php endforeach ?>
</table>

<input type="submit" class="submit button" value="<?php echo $this->translate('Update') ?>"/>

</form>

</div>

</div>
