<h2><?php echo $this->translate("News Feed") ?></h2>

<div class="ld-merger ld-feed">

<?php if (Ld_Auth::isAuthenticated()) : ?>
    <ul class="h6e-tabs">
        <li>
            <a href="<?php echo $this->url(array('action' => 'personal'), 'merger-feed') ?>"><?php
                echo $this->translate("Personal Feed");
        ?></a></li>
        <li>
            <a href="<?php echo $this->url(array('action' => 'public'), 'merger-feed') ?>"><?php
                echo $this->translate("Public Feed");
        ?></a></li>
        <li class="active more">
            <a href="<?php echo $this->url(array('controller' => 'settings', 'action' => 'index'), 'merger-settings') ?>"><?php
                echo $this->translate("Configure");
        ?></a></li>
    </ul>
<?php endif ?>

<div class="h6e-main">

<div class="h6e-page-content h6e-block has-tab">

<form method="post" action="" class="merger-settings">

<?php $this->notification() ?>

<table class="h6e-data">
    <tr>
        <th></th>
        <th><?php echo $this->translate("Personal Feed") ?></th>
        <th><?php echo $this->translate("Public Feed") ?></th>
    </tr>
    <?php foreach ($this->applications as $id => $feeds) : ?>
        <?php $instance = $this->site->getInstance($id); ?>
        <tr class="th2">
            <th class="title"><?php echo $instance->getName() ?></th>
            <td></td>
            <td></td>
        </tr>
        <?php foreach ($feeds as $feed) : $feedId = $feed['id']; ?>
            <tr>
                <td class="title"><?php echo $feed['title'] ?></td>
                <td>
                    <?php if ($feed['rel'] != 'public-feed') : ?>
                        <?php $checked = !isset($this->config['personal'][$id][$feedId]) || $this->config['personal'][$id][$feedId] == 1;  ?>
                        <input name="<?php echo "personal[$id][$feedId]" ?>" type="hidden" value="0"/>
                        <input name="<?php echo "personal[$id][$feedId]" ?>" type="checkbox" <?php if ($checked) echo 'checked="checked"' ?> value="1"/>
                    <?php endif ?>
                </td>
                <td>
                    <?php if ($feed['rel'] != 'personal-feed') : ?>
                        <?php $checked = !isset($this->config['public'][$id][$feedId]) || $this->config['public'][$id][$feedId] == 1;  ?>
                        <input name="<?php echo "public[$id][$feedId]" ?>" type="hidden" value="0"/>
                        <input name="<?php echo "public[$id][$feedId]" ?>" type="checkbox" <?php if ($checked) echo 'checked="checked"' ?> value="1"/>
                    <?php endif ?>
                </td>
            </tr>
        <?php endforeach ?>
    <?php endforeach ?>
</table>

<input type="submit" class="submit button" value="<?php echo $this->translate('Update') ?>"/>

</form>

</div>

</div>

<?php
$parameters = array('admin' => $this->admin, 'site' => $this->site);
echo $this->partial('partials/sidebar.phtml', $parameters);
?>

</div>