<?php if (isset($this->extension)) : ?>

    <h2>Remove <?php echo $this->package['name'] ?></h2>
        
    <p>You are going to remove an extension. Are you sure?</p>
    
    <form method="post" action="">
        <input type="hidden" name="id" value="<?php echo $this->escape($this->instance['id']) ?>"/>
        <input type="hidden" name="extension" value="<?php echo $this->escape($this->extension) ?>"/>
        <input type="hidden" name="referer" value="<?php echo $this->escape($_SERVER['HTTP_REFERER']) ?>"/>
        <input type="submit" class="submit" value="Remove"/>
    </form>

<?php endif ?>