<?php $this->instanceNavigation() ?>

<h2 class="h6e-entry-title">Manage</h2>

<h3>Overview</h3>

<table class="h6e-data">
    <tr>
        <th>package</th>
        <th>type</th>
        <th>version</th>
        <th>status</th>
        <th>action</th>
    </tr>
    <tr>
        <td><?php echo $this->instance->package ?></td>
        <td><?php echo $this->instance->type ?></td>
        <td><?php echo $this->instance->version ?></td>
        <td><?php echo $this->instance->update ? 'Need update' : 'Up to date' ?></td>
        <td>
        <?php if ($this->instance->update) : ?>
            <a href="<?php echo $this->instanceActionUrl('update') ?>?version=<?php echo $this->instance->update ?>">update</a>
        <?php endif ?>
        </td>
    </tr>
    <?php $extensions = $this->instance->extensions ?>
    <?php if (count($this->extensions) > 0) : ?>
        <tr><td colspan="5"><em>Extensions</em></td></tr>
        <?php foreach($this->extensions as $extension) : ?>
            <tr>
                <td><?php echo $extension->package ?></td>
                <td><?php echo $extension->type ?></td>
                <td><?php echo $extension->version ?></td>
                <td><?php echo $extension->update ? 'Need update' : 'Up to date' ?></td>
                <td>
                    <?php if ($extension->update) : ?>
                        <a href="<?php echo $this->instanceActionUrl('extensions') . '?update=' . $extension->path ?>">update</a>
                    <?php endif ?>
                    <a href="<?php echo $this->instanceActionUrl('extensions') . '?remove=' . $extension->path ?>">remove</a>
                </td>
            </tr>
        <?php endforeach ?>
    <?php endif ?>
</table>

<p>You can also:</p>

<ul>
    <li><a href="<?php echo $this->instanceActionUrl('backup') ?>">Backup this instance</a></li>
    <li><a href="<?php echo $this->instanceActionUrl('restore') ?>">Restore a backup</a></li>
    <?php if ($this->instance->restricted) : ?>
        <li><a href="<?php echo $this->instanceActionUrl('configure') ?>?restrict=0">Remove access restriction to this instance.</a></li>
    <?php else : ?>
        <li><a href="<?php echo $this->instanceActionUrl('configure') ?>?restrict=1">Restrict access to this instance.</a></li>
    <?php endif ?>
    <li><a href="<?php echo $this->instanceActionUrl('delete') ?>">Delete this instance</a></li>
</ul>