<p>Welcome!
    You own <strong><?php echo $this->site->slots ?></strong> slots on this site
    and <strong><?php echo $this->site->availableSlots ?></strong> slots are currently available.
</p>

<h2>Your applications</h2>

<ul class="blocks">
    <?php
    $i = 0;
    if (!empty($this->instances)) {
      foreach ($this->instances as $instance) {
          $manageUrl = $this->instanceActionUrl('manage', $instance->getPath());
          printf("<li class=\"%s\">", $instance->getPackageId());
          printf("<span>%s<br/>", $instance->getName());
          printf("- <a href=\"%s\">manage</a><br/>", $manageUrl);
          printf("- <a target=\"_blank\" href=\"%s\">launch</a>", $instance->getUrl());
          foreach ($instance->getLinks() as $link) {
              printf("<br/>- <a target=\"_blank\" href=\"%s\">%s</a>", $link['href'], $link['rel']);
          }
          printf("</span></li>");
          $i++;
      }
    }
    ?>
    <?php for ($j = $i; $j < $this->site->slots; $j++ ) : ?>
    <li class="empty">
        <a href="<?php echo $this->url(array('action' => 'new', 'site' => $this->site->id), 'instances-action') ?>">
            Add an application
        </a>
    </li>
    <?php endfor ?>
</ul>

<?php if (isset($this->repositories) && count($this->repositories) > 0) : ?>
    
    <h2>Your Repositories</h2>

    <?php echo $this->render('repositories/list.phtml') ?>

<?php endif; ?>

<?php if (empty($this->databases) || count($this->databases) == 0) : ?>

    <p><strong>Notice:</strong> You don't registered any database yet. A database is often needed to deploy new web application.</p>

<?php endif ?>

<?php if (empty($this->users) || count($this->users) == 0) : ?>

    <p><strong>Notice:</strong> You don't have any user registered yet. Registering users is necessary to password protect this admin and others applications.</p>

<?php endif ?>

<h2>Also</h2>

<ul>
    <li><a href="<?php echo $this->instanceActionUrl('manage', 'admin') ?>">Configure the Manager</a></li>
    <li><a href="<?php echo $this->url(array('controller' => 'repositories'), 'default') ?>">Manage Repositories</a></li>
    <li><a href="<?php echo $this->url(array('site' => $this->site->id), 'databases-action'); ?>">Manage Databases</a></li>
    <li><a href="<?php echo $this->url(array('site' => $this->site->id), 'users-action'); ?>">Manage Users</a></li>
</ul>