<h2>Add a new site</h2>

<form action="" method="post">
    
    <table>
    <tr>
        <td><label>Type</label></td>
        <td>
            <select name="type">
                <option value="remote">Remote</option>
            </select>
        </td>
    </tr>
    <tr>
        <td><label>Name</label></td>
        <td><input type="text" name="name" class="text" value=""/></td>
    </tr>
    <tr>
        <td><label>Endpoint</label></td>
        <td><input type="text" name="endpoint" class="text" value=""/></td>
    </tr>
    <tr>
        <td><label>Username</label></td>
        <td><input type="text" name="username" class="text" value=""/></td>
    </tr>
    <tr>
        <td><label>Password</label></td>
        <td><input type="text" name="password" class="text" value=""/></td>
    </tr>
    </table>

<input type="submit" class="submit" value="Add"/>
 
</form>