<h2><?php echo $this->translate("OpenID authentication") ?></h2>

<?php if ($this->mode == 'trust') : ?>

    <?php
    $site = sprintf('<a href="%1$s">%1$s</a>', $this->escape($this->siteRoot));
    $identity = sprintf('<a href="%1$s">%1$s</a>', $this->escape($this->identityUrl));
    ?>

    <p><?php printf(
        $this->translate('A site identifying as %1$s has asked us for confirmation that %2$s is your identity URL.', $site, $identity)) ?></p>

    <form method="post" action="">

        <input type="checkbox" name="forever">
        <label for="forever"><?php echo $this->translate("Remember for this site") ?></label>

        <br />
        <br />
        <input type="hidden" name="openid_action" value="trust">

        <?php foreach ($this->params as $key => $value) : ?>
            <input type="hidden" name="<?php echo $key ?>" value="<?php echo $value ?>"/>
        <?php endforeach ?>

        <input class="button" type="submit" name="allow" value="<?php echo $this->translate("Allow") ?>">
        <input class="button" type="submit" name="deny" value="<?php echo $this->translate("Deny") ?>">

    </form>

<?php else : ?>

    <p>This is the <strong>openid2.provider</strong> URL of the local identity provider. Don't panic!</p>

<?php endif ?>