<h2>Edit an user</h2>

<form method="post" action="">

    <table>
    <tr>
        <td><label>Full Name</label></td>
        <td><input type="text" name="fullname" class="text" value="<?php if (isset($this->user['fullname'])) echo $this->escape($this->user['fullname']) ?>"/></td>
    </tr>
    <tr>
        <td><label>Email</label></td>
        <td><input type="text" name="email" class="text" value="<?php if (isset($this->user['email'])) echo $this->escape($this->user['email']) ?>"/></td>
    </tr>
    </table>

    <input type="hidden" name="id" value="<?php echo $this->escape($this->username) ?>"/>

    <input type="submit" class="submit" value="Update"/>

</form>