<h2>Add a new user</h2>

<form method="post" action="">
    
    <table>
    <tr>
        <td><label>Full Name</label></td>
        <td><input type="text" name="fullname" class="text" value=""/></td>
    </tr>
    <tr>
        <td><label>Email</label></td>
        <td><input type="text" name="email" class="text" value=""/></td>
    </tr>
    <tr>
        <td><label>Username</label></td>
        <td><input type="text" name="username" class="text" value=""/></td>
    </tr>
    <tr>
        <td><label>Password</label></td>
        <td><input type="password" name="password" class="text" value=""/></td>
    </tr>
    </table>
     
    <input type="submit" class="submit" value="Add"/>

</form>