<h2>Databases Connections</h2>

<?php if (empty($this->databases) || count($this->databases) == 0) : ?>

    <p>None</p>

<?php else : ?>

    <?php $this->headScript()->offsetSetFile('ld-data', Zend_Registry::get('site')->getUrl('js') . '/ld/ld-data.js'); ?>

    <table class="h6e-data">

    <tr>
       <th>Type</th>
       <th>Host</th>
       <th>Name</th>
       <th colspan="2">Action</th>
    </tr>

    <tbody>

    <?php foreach ($this->databases as $id => $database) : ?>

        <tr>
            <td><?php echo $this->escape($database['type']) ?></td>
            <td><?php echo $this->escape($database['host']) ?></td>
            <td><?php echo $this->escape($database['name']) ?></td>
            <td>
                <a href="<?php echo $this->url(array('action' => 'edit', 'id' => $id )); ?>">edit</a>
            </td>
            <td>
                <a href="<?php echo $this->url(array('action' => 'delete', 'id' => $id )); ?>">delete</a>
            </td>
        </tr>

    <?php endforeach ?>

    </tbody>

    </table>

<?php endif ?>

<h3>You can</h3>

<ul>
    <li><a href="<?php echo $this->url(array('action' => 'new'), 'default'); ?>">Add a new database connection</a></li>
</ul>