<?php if (isset($this->params['jquery']) && $this->params['jquery'] === true ) : ?>
    <script type="text/javascript" src="<?php echo Ld_Ui::getJsUrl('/jquery/jquery.js', 'jquery') ?>"></script>
<?php endif ?>

<?php if (isset($this->params['ld-js']) && $this->params['ld-js'] === true ) : ?>
    <script type="text/javascript" src="<?php echo Ld_Ui::getJsUrl('/ld/ld.js', 'admin') ?>"></script>
<?php endif ?>

<?php if (isset($this->params['style']) && $this->params['style'] === true ) : ?>
    <style type="text/css">
        @import "<?php echo Ld_Ui::getCssUrl('/ld-ui/ld-bars.css', 'ld-ui') ?>";
    </style>
<?php endif ?>

<div id="ld-super-bar" class="h6e-super-bar">

    <div class="h6e-super-bar-inner">

        <div class="a">
            <ul class="instances">

<?php

            foreach ($this->applications as $id => $application) {

                if ($application == null) {
                    continue;
                }

                $settingsUrl = Ld_Ui::getAdminUrl(array(
                    'module' => 'slotter', 'controller' => 'instance', 'action' => 'status', 'id' => $id
                ), 'instance-action');
                $settings = strpos($_SERVER["REQUEST_URI"], $settingsUrl) !== false;

                $adminUrl = null;
                foreach ($application->getLinks() as $link) {
                      if ($link['type'] == 'text/html' && $link['title'] == 'admin') {
                          $adminUrl = $link['href'];
                          break;
                      }
                }

                $admin = isset($adminUrl) && strpos($_SERVER["REQUEST_URI"], $adminUrl) !== false;

                $className = $application->getPackageId();

                printf("                " . '<li id="app_%s" class="%s">', $id, $className);

                if ($application->isCurrent() && !$settings && !$admin) {
                    printf('<strong><a href="%s">%s</a></strong>' . "\n  ", $application->getUrl(), $application->getName());
                } else {
                    printf('<a href="%s">%s</a>', $application->getUrl(), $application->getName());
                }

                if ($this->isAdmin && $id != 'admin' && ($application->isCurrent() || $settings || $admin)) {
                    if (isset($adminUrl) || isset($settingsUrl)) {
                        echo "&nbsp; • &nbsp;";
                    }
                    if (isset($adminUrl)) {
                        $link = sprintf('<a href="%s">%s</a>', $adminUrl, $this->translate("Admin"));
                        if ($admin) {
                            printf('<strong>%s</strong>', $link);
                        } else {
                            printf('%s', $link);
                        }
                    }
                    if (isset($adminUrl) && isset($settingsUrl)) {
                        printf(' | ');
                    }
                    if (isset($settingsUrl)) {
                        $link = sprintf('<a class="ld-settings" href="%s">%s</a>', $settingsUrl, $this->translate("Settings"));
                        if ($settings) {
                            printf('<strong>%s</strong>', $link);
                        } else {
                            printf('%s', $link);
                        }
                    }
                }

                printf("</li>\n");

            }

?>

            </ul>
        </div>

        <div class="b">

        </div>

    </div>

</div>

<?php if (defined('LD_AJAX_PANELS') && constant('LD_AJAX_PANELS')) : ?>

<style type="text/css">
    .ld-panel-container {
        width:100%;
        height:100%;
        top:0;
        left:0;
        position:fixed;
        background-color:rgba(0,0,0,0.5);
    }
    .ld-panel-container .ld-panel {
        margin:auto;
        margin-top:150px;
        width:700px;
        padding:25px;
    }
    .ld-panel-container .ld-panel .ld-panel-content {
        background:white;
        max-height:450px;
        overflow:auto;
    }
</style>

<div class="ld-panel-container" style="display:none">
    <div class="ld-panel">
    </div>
</div>

<script type="text/javascript" src="<?php echo Ld_Ui::getJsUrl('/jquery/jquery.js', 'jquery') ?>"></script>
<script type="text/javascript" src="<?php echo Ld_Ui::getJsUrl('/ld/ld.js', 'admin') ?>"></script>

<script type="text/javascript">
(function($) {
    $(document).ready(function($){
        $('a.ld-settings').click(function(e) {
            $(".ld-panel-container").show();
            $(".ld-panel-container .ld-panel").load($(this).attr('href') + " .ld-panel > *", null, function() {
                Ld.instanceMenu($);
            });
            return false;
        });
    });
})(jQuery);
</script>

<?php endif ?>
