<?php
$siteMenus = array();
if ($this->site->isChild() && $this->site->hasParentSite()) {
    $siteMenus[] = array('site' => $this->site->getParentSite(), 'class' => 'ld-site-menu');
    $siteMenus[] = array('site' => $this->site, 'class' => 'ld-subsite-menu');
} else {
    $siteMenus[] = array('site' => $this->site, 'class' => 'ld-site-menu');  
}
?>

<?php foreach ($siteMenus as $menu) : extract($menu); ?>

<div class="ld-top-menu ld-main-menu <?php echo $class ?>" style="display:none">
    <div class="ld-top-menu-inner ld-main-menu-inner">
        <?php
        $admin = $site->getAdmin();
        $applications = $site->getApplicationsInstances(array('admin'));
        ?>
        <?php if (!empty($applications)) : ?>
        <div class="applications">
        <h3><?php echo $this->translate('Applications') ?></h3>
        <ul class="instances"> 
            <?php foreach ($applications as $id => $application) : ?>
                <?php
                if (!$application->isVisible()) {
                    continue;
                }
                $className = $application->getPackageId();
                $inlineStyle = '';
                if ($icon = $application->getIcon('icon')) {
                    $inlineStyle .= "background-image:url($icon);";
                }
                printf('<li id="app_%s" class="%s" style="%s">', $id, $className, $inlineStyle);
                printf('<a href="%s"><span class="name">%s</span><br /><span class="path">/%s/</span></a>',
                    $application->getUrl(),  $application->getName(), $application->getPath());
                printf("</li>\n");
                ?>
            <?php endforeach; ?>
        </ul>
        </div>
        <?php endif ?>

        <div class="ladistribution">
        <h3>La Distribution</h3>
        <?php
        $pages = array();
        $pages[] = array('label' => "Home", 'class' => "home", 'route' => array('module' => 'slotter', 'controller' => 'index'));
        if (!defined('LD_NEWS_FEED') || constant('LD_NEWS_FEED')) {
            $pages[] = array('label' => "News Feed", 'class' => "timeline", 'route' => array('module' => 'merger', 'controller' => 'index'));
        }
        if (Ld_Ui::isAdmin()) {
            $pages[] = array('label' => "Users", 'class' => "users", 'route' => array('module' => 'slotter', 'controller' => 'users'));
            $pages[] = array('label' => "Settings", 'class' => "settings", 'route' => array('module' => 'slotter', 'controller' => 'settings'));
        }
        ?>
        <ul class="instances">
            <?php foreach ($pages as $page) : ?>
                <li class="<?php echo $page['class'] ?>"><a href="<?php echo $admin->buildUrl($page['route']) ?>">
                    <span class="name"><?php echo $this->translate($page['label']) ?></span><br/>
                    <span class="path">&nbsp;</span></a></li>
            <?php endforeach ?>
        </ul>
        </div>

    </div>
</div>

<?php endforeach ?>

<?php if (Ld_Ui::isAdmin() && Zend_Registry::isRegistered('application') && $application = Zend_Registry::get('application')) : ?>
<div class="ld-top-menu ld-app-menu" style="display:none">
    <div class="ld-top-menu-inner ld-app-menu-inner">
        <?php $packageInfos = $application->getManifest()->getInfos() ?>
        <h3><?php echo $packageInfos['name'] ?></h3>
        <ul class="instances">
            <?php if ($adminUrl = $application->getAdminUrl()) : ?>
                <li class="admin"><a href="<?php echo $adminUrl ?>">
                    <span class="name"><?php echo $this->translate("Admin") ?></span>
                    <span class="path">&nbsp;</span>
                </a></li>
            <?php endif ?>
            <li class="settings"><a href="<?php echo Ld_Ui::getApplicationSettingsUrl() ?>">
                <span class="name"><?php echo $this->translate("Settings") ?></span>
                <span class="path">&nbsp;</span>
            </a></li>
        </ul>
    </div>
</div>
<?php endif ?>
