<div class="h6e-top-bar">
    <div class="h6e-top-bar-inner">
        <div class="a">
            <a class="ld-site-name" href="<?php echo $this->site->getUrl() ?>"><?php echo $this->site->getName() ?></a>
        </div>
        <div class="b">
        <?php if (Ld_Auth::isAuthenticated() && Ld_Auth::isAnonymous()) : ?>

            <a href="<?php echo $this->completeUrl ?>"><?php echo empty($user['fullname']) ? $user['username'] : $user['fullname'] ?></a>
            <a href="<?php echo $this->logoutUrl ?>"><?php echo $this->translate("Log Out") ?></a>

        <?php elseif (Ld_Auth::isAuthenticated() && $user = Ld_Auth::getUser()) : ?>

            <a href="<?php echo $this->userUrl ?>"><?php echo empty($user['fullname']) ? $user['username'] : $user['fullname'] ?></a>
            <a href="<?php echo $this->logoutUrl ?>"><?php echo $this->translate("Log Out") ?></a>

        <?php else : ?>

            <a class="h6e-login" href="<?php echo $this->loginUrl ?>"><?php echo $this->translate("Log In") ?></a>
            <?php if ($this->site->getConfig('open_registration')) : ?>
                <a href="<?php echo $this->registerUrl ?>"><?php echo $this->translate("Register") ?></a>
            <?php endif ?>
        <?php endif ?>

        </div>
    </div>
</div>
