<div class="ld-panel">

<div class="ld-panel-content h6e-block no-tab">

<h3><?php echo sprintf( $this->translate("Authorize \"%s\" to use your account?"), $this->client['application_name'] ) ?></h3>

<p><?php echo $this->translate("This application will be able to:") ?></p>

<?php $scopes = explode(" ", $this->authParams['scope']); ?>
<ul>
    <?php if (in_array('profile', $scopes)) : ?><li><?php
        echo $this->translate("Read your basic profile.") ?></li><?php endif ?>
    <?php if (in_array('email', $scopes)) : ?><li><?php
        echo $this->translate("Read your email address.") ?></li><?php endif ?>
</ul>

<form method="post" action="">
  <?php foreach ($this->authParams as $key => $value) : ?>
      <input type="hidden" name="<?php echo $this->escape($key); ?>" value="<?php echo $this->escape($value); ?>" />
  <?php endforeach; ?>
  <input class="button" type="submit" name="accept" value="<?php echo $this->okLabel ?>" />
  <input class="button" type="submit" name="accept" value="<?php echo $this->cancelLabel ?>" />
</form>

</div>

</div>
