<h2><?php echo $this->translate("Users") ?></h2>

<?php $this->partialNavigationMenu('Users') ?>

<div class="ld-panel-content h6e-block">

<h3><?php echo $this->translate("Delete an user") ?></h3>

<p><?php echo $this->translate("Are you sure you want to delete this user?") ?></p>

<form method="post" action="">

    <input type="hidden" name="username" value="<?php echo $this->escape($this->username) ?>"/>
    <input type="submit" class="submit button ld-button" value="<?php echo $this->translate("Delete") ?>"/>

</form>

</div>
