<h2><?php echo $this->translate("Edit user infos") ?></h2>

<form method="post" action="">

    <h3><?php echo $this->translate("Infos") ?></h3>

    <table class="ld-form">
    <tr>
        <th><label><?php echo $this->translate("Full Name") ?></label></td>
        <td><input type="text" name="fullname" class="text" value="<?php if (isset($this->user['fullname'])) echo $this->escape($this->user['fullname']) ?>"/></td>
    </tr>
    <tr>
        <th><label><?php echo $this->translate("Email") ?></label></td>
        <td><input type="text" name="email" class="text" value="<?php if (isset($this->user['email'])) echo $this->escape($this->user['email']) ?>"/></td>
    </tr>
    </table>

    <?php if ($this->currentUser['username'] == $this->user['username']) : ?>

    <h3><?php echo $this->translate("Change password") ?></h3>

    <p><em><?php echo $this->translate("If you would like to change the password type a new one. Otherwise leave this blank.") ?></em></p>

    <table class="ld-form">
    <!--
    <tr>
        <td><label>Current password</label></td>
        <td><input type="password" name="current_password" class="text" value=""/></td>
    </tr>
    -->
    <tr>
        <th><label><?php echo $this->translate("New password") ?></label></td>
        <td><input type="password" name="new_password" class="text" value="" autocomplete="off"/></td>
    </tr>
    <tr>
        <th><label><?php echo $this->translate("New password again") ?></label></td>
        <td><input type="password" name="new_password_again" class="text" value="" autocomplete="off"/></td>
    </tr>
    </table>

    <?php endif ?>

    <input type="hidden" name="id" value="<?php echo $this->escape($this->username) ?>"/>

    <input type="submit" class="submit" value="<?php echo $this->translate("Update") ?>"/>

</form>

<?php if ($this->currentUser['username'] == $this->user['username']) : ?>

<hr/>

<h3><?php echo $this->translate("Identities") ?></h3>

<?php if (isset($this->user['identities']) && count($this->user['identities']) > 0) : ?>

    <table class="h6e-data">
    <?php foreach ($this->user['identities'] as $identity) : ?>
        <tr>
            <td><?php echo $this->escape($identity) ?></td>
            <td><a href="<?php echo $this->url(array('action' => 'remove-identity', 'identity' => urlencode($identity))) ?>"><?php echo $this->translate("remove") ?></td>
        </tr>
    <?php endforeach ?>
    </table>

<?php else : ?>

    <p><em>You don't have any other identities registered yet. You can add new OpenID identities with the form below.</em></p>

<?php endif ?>

<form method="post" action="<?php echo $this->url(array('action' => 'add-identity')) ?>">

    <table style="width:auto">
        <tr>
            <th><label for="add_new_identity"><?php echo $this->translate("Add an identity:") ?></label></th>
            <td><input id="add_new_identity" type="text" name="openid_identifier" value="" /></td>
            <td><input type="submit" value="<?php echo $this->translate("Add") ?>"/></td>
        </tr>
    </table>

</form>

<?php endif ?>
