<h2><?php echo $this->translate("Edit user infos") ?></h2>

<form method="post" action="" autocomplete="off">

    <h3><?php echo $this->translate("Infos") ?></h3>

    <table class="ld-form">
    <tr>
        <th><label for="edit-user-fullname"><?php echo $this->translate("Full Name") ?></label></td>
        <td><input id="edit-user-fullname" type="text" name="fullname" class="text" value="<?php
            if (isset($this->user['fullname'])) echo $this->escape($this->user['fullname']) ?>"/></td>
    </tr>
    <tr>
        <th><label for="edit-user-email"><?php echo $this->translate("Email") ?></label></td>
        <td><input id="edit-user-email" type="text" name="email" class="text" value="<?php
            if (isset($this->user['email'])) echo $this->escape($this->user['email']) ?>"/></td>
    </tr>
    </table>

    <?php if ($this->currentUser['username'] == $this->user['username']) : ?>

    <h3><?php echo $this->translate("Change password") ?></h3>

    <p><em><?php echo $this->translate("If you would like to change the password type a new one. Otherwise leave this blank.") ?></em></p>

    <table class="ld-form">
    <!--
    <tr>
        <td><label>Current password</label></td>
        <td><input type="password" name="current_password" class="text" value=""/></td>
    </tr>
    -->
    <tr>
        <th><label for="edit-user-password"><?php echo $this->translate("New password") ?></label></td>
        <td><input id="edit-user-password" type="password" name="new_password" class="text" value="" autocomplete="off"/></td>
    </tr>
    <tr>
        <th><label for="edit-user-password-2"><?php echo $this->translate("New password again") ?></label></td>
        <td><input id="edit-user-password-2" type="password" name="new_password_again" class="text" value="" autocomplete="off"/></td>
    </tr>
    </table>

    <?php endif ?>

    <input type="hidden" name="id" value="<?php echo $this->escape($this->username) ?>"/>

    <input type="submit" class="submit button ld-button" value="<?php echo $this->translate("Update") ?>"/>

</form>

<?php if ($this->currentUser['username'] == $this->user['username']) : ?>

<hr/>

<h3><?php echo $this->translate("OpenID Server") ?></h3>

<p><?php echo $this->translate("You can log on OpenID enabled websites using the bundled OpenID Server.") ?></p>

<p><?php echo $this->translate("Your identity URL:") ?> <strong><?php echo $this->escape($this->identity) ?></strong></p>

<hr/>

<h3><?php echo $this->translate("Other OpenID Identities") ?></h3>

<p><?php echo $this->translate("You can log on this website using other OpenID identities.") ?></p>

<?php if (isset($this->user['identities']) && count($this->user['identities']) > 0) : ?>

    <table class="h6e-data">
    <?php foreach ($this->user['identities'] as $identity) : ?>
        <tr>
            <td><?php echo $this->escape($identity) ?></td>
            <td><a href="<?php echo $this->url(array('action' => 'remove-identity', 'identity' => urlencode($identity))) ?>"><?php echo $this->translate("remove") ?></td>
        </tr>
    <?php endforeach ?>
    </table>

<?php else : ?>

    <p><em><?php echo $this->translate(
        "You don't have any OpenID identity registered yet. You can add new identities with the form below."
    ) ?></em></p>

<?php endif ?>

<form method="post" action="<?php echo $this->url(array('action' => 'add-identity')) ?>">

    <table class="ld-form">
        <tr>
            <th><label for="add_new_identity"><?php echo $this->translate("Add an identity:") ?></label></th>
            <td><input id="add_new_identity" type="text" name="openid_identifier" value="" size="50" /></td>
            <td><input type="submit" class="submit button ld-button" value="<?php echo $this->translate("Add") ?>"/></td>
        </tr>
    </table>

</form>

<?php endif ?>
