<h2><?php echo $this->translate("Users") ?></h2>

<?php if (empty($this->users)) : ?>

    <p><?php echo $this->translate("None|masc") ?></p>

<?php else : ?>

<form action="" method="post">

<table class="h6e-data">

   <tr>
       <th><?php echo $this->translate("Username") ?></th>
       <th><?php echo $this->translate("Full Name") ?></th>
       <?php /*
       <?php foreach ($this->applications as $application) : ?>
           <th style="text-align:center"><?php echo $application['name'] ?><br/><small>/<?php echo $application['path'] ?>/</small></th>
       <?php endforeach ?>
       */ ?>

       <?php if ($this->userRole == 'admin') : ?>
           <th colspan="2"><?php echo $this->translate("Actions") ?></th>
       <?php endif ?>

   </tr>

<?php foreach ($this->users as $user) : ?>

    <tr>
        <td><?php echo $user['username'] ?></td>
        <td><?php echo $user['fullname'] ?></td>
        
        <?php /*
        <?php foreach ($this->applications as $application) : ?>
            <td style="text-align:center">
            <?php if (!empty($application['roles'])) : ?>

                <select name="roles[<?php echo $application['path'] ?>][<?php echo $user['username'] ?>]">
                    <?php foreach ($application['roles'] as $role) : ?>
                        <?php
                        $username = $user['username'];
                        $selected = isset($application['userRoles'][$username]) && $application['userRoles'][$username] == $role ?
                            'selected="selected"' : '';
                        ?>
                        <option <?php echo $selected ?> value="<?php echo $role ?>"><?php echo ucfirst($role) ?></option>
                    <?php endforeach ?>
                </select>

            <?php else : ?>

                <em style="color:#999">N/A</em>

            <?php endif ?>
            </td>
       <?php endforeach ?>
       */ ?>
       
       <?php if ($this->userRole == 'admin') : ?>
           <td>
               <a href="<?php echo $this->url(array('action' => 'edit', 'id' => $user['username'] )); ?>"><?php
                   echo $this->translate("edit");
               ?></a>
           </td>
           <td>
               <a href="<?php echo $this->url(array('action' => 'delete', 'id' => $user['username'] )); ?>"><?php
                   echo $this->translate("delete");
               ?></a>
           </td>
       <?php endif ?>

    </tr>

<?php endforeach ?>

</table>

<?php /*
<input type="submit" class="submit button" value="Update"/>
*/ ?>

</form>

<?php endif ?>

<br />

<h3><?php echo $this->translate("You can:") ?></h3>

<ul>
    <li><a href="<?php echo $this->url(array('action' => 'new')); ?>"><?php echo $this->translate("Add a new user") ?></a></li>
</ul>
