<h2><?php echo $this->translate("Users") ?></h2>

<?php $this->partialNavigationMenu('Users') ?>

<div class="ld-panel-content h6e-block">

    <form method="post" action="">

        <h3><?php echo $this->translate("Invite new users") ?></h3>

        <p><?php echo $this->translate("Invitations had been sent. Users will receive an email with all informations on how to finish their registration.") ?></p>

    </form>

</div>
