<h2><?php echo $this->translate("Users") ?></h2>

<div class="ld-panel-content h6e-block no-tab">

    <form method="post" action="">

        <h3><?php echo $this->translate("Invite new users") ?></h3>

        <?php if (empty($this->emails)) : ?>

        <p><?php echo $this->translate("Enter user email adresses. Ideally one per line.") ?>
            <!-- <em>(<?php echo $this->translate("but practically you can paste whatever you want") ?>)</em>. --></p>

        <textarea rows="10" cols="60" style="font-size:1.25em" name="emails"></textarea>

        <p>
            <input type="submit" class="submit button ld-button" value="<?php echo $this->translate("Continue") ?>"/>
        </p>

        <p><em><?php echo $this->translate("You can safely go to next step, no email will be sent") ?></em></p>

        <?php else : ?>

            <p><?php echo $this->translate("Confirm the list of users you want to invite:") ?></p>

            <table class="h6e-data">
                <tr>
                    <th></th>
                    <th></th>
                    <th><?php echo $this->translate("Email") ?></th>
                    <th><?php echo $this->translate("Username") ?></th>
                    <th><?php echo $this->translate("Status") ?></th>
                    <th><?php echo $this->translate("Role") ?></th>
                </tr>
            <?php foreach ($this->emails as $email => $user) : ?>
                <?php if (isset($user)) : ?>
                    <tr>
                        <td><input type="checkbox" disabled="disabled" name="emails[]" value="<?php echo $email ?>"/></td>
                        <td class="avatar"><?php echo Ld_Ui::getAvatar(array('email' => $email), 16) ?></td>
                        <td><?php echo $this->escape($email) ?></td>
                        <td><?php echo $this->escape($user['username']) ?></td>
                        <?php if (!isset($user['activated']) || $user['activated'] == true) : ?>
                            <td><?php echo $this->translate("Already registered") ?></td>
                        <?php else : ?>
                            <td><?php echo $this->translate("Activation pending") ?></td>
                        <?php endif ?>
                        <td><?php echo ucfirst( $this->userRoles[ $user['username'] ] ) ?></td>
                    </tr>
                <?php else : ?>
                <tr>
                    <td><input type="checkbox" checked="checked" name="emails[]" value="<?php echo $email ?>"/></td>
                    <td><?php echo Ld_Ui::getAvatar(array('email' => $email), 16) ?></td>
                    <td><?php echo $this->escape($email) ?></td>
                    <td>/</td>
                    <td><?php echo $this->translate("Not yet registered") ?></td>
                    <td>
                    <select name="roles[<?php echo $this->escape($email) ?>]">
                        <?php foreach ($this->roles as $role) : ?>
                            <?php
                            $selected = $role == 'user' ? 'selected="selected"' : '';
                            ?>
                            <option <?php echo $selected ?> value="<?php echo $role ?>"><?php echo ucfirst($role) ?></option>
                        <?php endforeach ?>
                    </select>
                </tr>
                <?php endif ?>
            <?php endforeach ?>
            </table>

            <input type="hidden" name="confirm" value="1"/>
            <p><input type="submit" class="submit button ld-button" value="<?php echo $this->translate("Add users and send invitations") ?>"/></p>

        <?php endif ?>

    </form>

</div>
