<h2><?php echo $this->translate("Add a new user") ?></h2>

<form method="post" action="">

    <table>
    <tr>
        <td><label><?php echo $this->translate("Full Name") ?></label></td>
        <td><input type="text" name="fullname" class="text" value=""/></td>
    </tr>
    <tr>
        <td><label><?php echo $this->translate("Email") ?></label></td>
        <td><input type="text" name="email" class="text" value=""/></td>
    </tr>
    <tr>
        <td><label><?php echo $this->translate("Username") ?></label></td>
        <td><input type="text" name="username" class="text" value=""/></td>
    </tr>
    <tr>
        <td><label><?php echo $this->translate("Password") ?></label></td>
        <td><input type="password" name="password" class="text" value=""/></td>
    </tr>
    </table>

    <input type="submit" class="submit" value="<?php echo $this->translate("Add") ?>"/>

</form>