<h2><?php echo $this->translate("Locales") ?></h2>

<div class="ld-panel">

<?php $this->partialNavigationMenu('Settings') ?>

<div class="ld-panel-content">

<form action="<?php echo $this->url() ?>" method="post">

    <fieldset>

    <?php foreach ($this->allLocales as $id => $label) : ?>

        <input type="checkbox" id="locale-<?php echo $id ?>" name="locales[<?php echo $id ?>]"
            <?php if (isset($this->locales[$id])) : ?> checked="checked"<?php endif ?> />
        <label for="locale-<?php echo $id ?>"><?php echo $this->escape($label) ?></label>

    <?php endforeach ?>

    </fieldset>

    <p><input class="submit button" type="submit" value="<?php echo $this->translate("Update") ?>"/></p>

</form>

</div>

</div>