<?php $this->instanceWidget() ?>

<div class="ld-panel">

<?php $this->instanceNavigation() ?>

<div class="ld-panel-content h6e-block">

<?php if (defined('LD_APPEARANCE') && constant('LD_APPEARANCE') && !empty($this->colorSchemes)) : ?>

<form action="" method="post">

    <h3><?php echo $this->translate("Colors") ?></h3>

    <?php echo $this->notification() ?>

    <?php echo $this->partial('partials/color-schemes.phtml', array('colorSchemes' => $this->colorSchemes, 'colors' => $this->colors)) ?>

    <input type="submit" class="submit button ld-button" value="<?php echo $this->translate("Update") ?>"/>

</form>

<?php else : ?>

    <p><?php echo $this->translate("Not supported") ?></p>

<?php endif ?>

</div> <!-- .ld-panel-content -->

</div> <!-- .ld-panel -->
