<?php $this->instancesList(false) ?>

<div class="ld-panel">

<?php $this->instanceNavigation() ?>

<div class="ld-panel-content h6e-block">

<h3><?php echo $this->translate('Existing backups') ?></h3>

<table class="h6e-data ld-data">
    <tr class="th1">
        <th><?php echo $this->translate('File') ?></th>
        <th><?php echo $this->translate('Size') ?></th>
        <th colspan="3"><?php echo $this->translate('Actions') ?></th>
    </tr>
    <?php
    if (empty($this->backups) || count($this->backups) == 0) {
        ?>
        <tfoot>
            <tr>
                <td>None</td>
                <td>/</td>
                <td colspan="3">/</td>
            </tr>
        </tfoot>
        <?php
    }
    foreach ($this->backups as $backup) {
        $downloadUrl = $this->instanceActionUrl('backups') . '?download=' . $backup['filename'];
        $restoreUrl = $this->instanceActionUrl('backups') . '?restore=' .   $backup['filename'];
        $deleteUrl = $this->instanceActionUrl('backups') . '?delete=' .   $backup['filename'];
        ?>
        <tr>
            <td><?php echo $backup['filename'] ?></td>
            <td><?php echo $backup['size'] ?></td>
            <td><a href="<?php echo $downloadUrl ?>"><?php echo $this->translate('download') ?></a></td>
            <td><a href="<?php echo $restoreUrl ?>"><?php echo $this->translate('restore') ?></a></td>
            <td><a href="<?php echo $deleteUrl ?>"><?php echo $this->translate('delete') ?></a></td>
        </tr>
        <?php
    }
    ?>
</table>

<h3><?php echo $this->translate('New backup') ?></h3>

<form action="<?php echo $this->url() ?>" method="post">
    <input type="hidden" name="dobackup" value="now" />
    <input type="submit" class="submit button ld-button" value="<?php echo $this->translate('Generate a backup now') ?>" />
</form>

<br />

<!--
    
<h3><?php echo $this->translate('Upload') ?></h3>

<form action="<?php echo $this->url() ?>" method="post" enctype="multipart/form-data">
    <input type="file" name="archive" />
    <input name="upload" type="submit" class="submit" value="<?php echo $this->translate('Upload') ?>" />
</form>

-->

</div> <!-- .ld-panel-content -->

</div> <!-- .ld-panel -->
