<h2><?php echo $this->translate("Clone an application") ?></h2>

<div class="ld-panel-content h6e-block no-tab">

<h3><?php echo $this->translate('Clone from a backup') ?></h3>

<form method="post" enctype="multipart/form-data" action="">

    <table>
        <tr>
            <td rowspan="3"><label><?php echo $this->translate('Backup (zip file please)') ?></label></td>
            <td><label><?php echo $this->translate('Local (file)') ?></label></td>
            <td><input type="file" name="file"/><br/></td>
        </tr>
        <tr><td>or</td></tr>
        <tr>
            <td><label><?php echo $this->translate('Remote (URL)') ?></label></td>
            <td><input class="text" size="25" type="text" name="url"/></td>
        </tr>
        <tr>
            <td colspan="2"><label><?php echo $this->translate('Path') ?></label></td>
            <td><input class="text" size="25" type="text" name="preferences[path]" value="clone" /></td>
        </tr>
    </table>

    <input name="upload" class="submit button ld-button" type="submit" value="<?php echo $this->translate('Clone') ?>"/>

</form>

</div>
