<h2>Clone an application.</h2>

<form method="post" enctype="multipart/form-data" action="">

    <table>
        <tr>
            <td><label>Backup (zip file please)</label></td>
            <td><input type="file" name="file"/></td>
        </tr>
        <tr>
            <td><label>Path</label></td>
            <td><input class="text" size="25" type="text" name="preferences[path]" value="clone" /></td>
        </tr>
    </table>

    <p>
        <input name="upload" class="submit" type="submit" value="Upload &amp; Clone"/>
    </p>

</form>