<?php $this->instancesList(false) ?>

<div class="ld-panel">

<?php $this->instanceNavigation() ?>

<div class="ld-panel-content">

<?php if (!empty($this->preferences)) : ?>

<form method="post" action="<?php echo $this->url() ?>">
    
    <input type="hidden" name="id" value="<?php echo $this->escape($this->instance->id) ?>"/>
    
    <?php $this->preferencesRenderer($this->preferences, $this->configuration, 'configuration'); ?>
    
    <input type="submit" class="submit button" value="<?php echo $this->translate('Update') ?>"/>

</form>

<?php else : ?>

<p><?php echo $this->translate('No preference available for this application.') ?></p>

<?php endif ?>

</div> <!-- .ld-panel-content -->

</div> <!-- .ld-panel -->
