<?php $this->instanceWidget() ?>

<div class="ld-panel-content h6e-block no-tab">

<h3><?php echo $this->translate('Are you sure you want to delete this application?') ?></h3>

<?php if ($this->instance->package == 'admin') : ?>
    <p><strong>Notice:</strong> deleting the admin application is not a good idea!</p>
<?php endif ?>

<form method="post" action="<?php echo $this->url() ?>">

    <input type="submit" class="submit button" value="<?php echo $this->translate('Delete') ?>"/>

</form>

</div>
