<h2>Delete an application</h2>

<p>Are you sure you want to delete this application?</p>

<?php if ($this->instance->package == 'admin') : ?>
    <p><strong>Notice:</strong> deleting the admin application is not a good idea!</p>
<?php endif ?>

<form method="post" action="">
    
    <input type="hidden" name="id" value="<?php echo $this->escape($this->instance->id) ?>"/>
    <input type="submit" class="submit" value="Delete"/>

</form>