<?php $this->instanceWidget() ?>

<div class="ld-panel">

<?php $this->instanceNavigation() ?>

<div class="ld-panel-content h6e-block">

<h3><?php printf($this->translate('Uninstall %s?'), $this->extension->getPackage()->getName()) ?></h3>

<p><?php echo $this->translate('You are going to uninstall an extension. Are you sure?') ?></p>

<form method="post" action="<?php echo $this->url() ?>">
    <input type="hidden" name="remove" value="<?php echo $this->escape($this->extension->getPackageId()) ?>"/>
    <input type="submit" class="submit button ld-button" name="confirm" value="<?php echo $this->translate('Uninstall') ?>"/>
</form>

</div> <!-- .ld-panel-content -->

</div> <!-- .ld-panel -->
