<?php $this->instancesList(false) ?>

<div class="ld-panel">

<?php $this->instanceNavigation() ?>

<div class="ld-panel-content">

<?php if (isset($this->extension)) : ?>

    <h3><?php printf($this->translate('Install %s?'), $this->package->name) ?></h3>

    <?php if (isset($this->installed)) : ?>

        <p><?php echo $this->translate('This extension is already installed') ?></p>

    <?php else : ?>

        <p><?php echo $this->translate('You are going to install an extension. Are you sure?') ?></p>

        <form method="post" action="<?php echo $this->instanceActionUrl('extensions') ?>">
            <input type="hidden" name="id" value="<?php echo $this->escape($this->instance->path) ?>"/>
            <input type="hidden" name="add" value="<?php echo $this->escape($this->extension) ?>"/>

            <?php if (!empty($this->preferences)) : ?>
                <h3>Preferences</h3>
                <?php $this->preferencesRenderer($this->preferences, array(), 'preferences'); ?>
            <?php endif ?>

            <?php if (isset($_SERVER['HTTP_REFERER'])) : ?>
                <input type="hidden" name="referer" value="<?php echo $this->escape($_SERVER['HTTP_REFERER']) ?>"/>
            <?php endif ?>

            <input type="submit" class="submit" value="<?php echo $this->translate('install') ?>"/>
        </form>

    <?php endif ?>

<?php else : ?>

    <?php if (isset($this->extensions) && count($this->extensions) > 0) : ?>

        <h3><?php echo $this->translate('Install an extension') ?></h3>

        <ul>
        <?php
        foreach ($this->extensions as $id => $extension) {
            $url = $this->instanceActionUrl('extensions') . '?add=' . $id;
            printf("<li><a href=\"%s\">%s</a></li>", $url, $extension->name);
        }
        ?>
        </ul>
    
    <?php else : ?>
        
        <p><?php echo $this->translate('No extension available for this application.') ?></p>
        
    <?php endif; ?>

<?php endif ?>

</div> <!-- .ld-panel-content -->

</div> <!-- .ld-panel -->
