<?php $this->instanceWidget() ?>

<div class="ld-panel">

<?php $this->instanceNavigation() ?>

<div class="ld-panel-content h6e-block">

<h3><?php printf($this->translate('Update %s?'), $this->extension->getPackage()->getName()) ?></h3>

<p><?php echo $this->translate('You are going to update an extension. Are you sure?') ?></p>

<form method="post" action="<?php echo $this->url() ?>">
    <input type="hidden" name="update" value="<?php echo $this->escape($this->extension->getPackageId()) ?>"/>
    <input type="submit" class="submit button" name="confirm" value="<?php echo $this->translate('Update') ?>"/>
    <input type="submit" class="submit cancel button" name="cancel" value="<?php echo $this->translate('Cancel') ?>"/>
</form>

</div> <!-- .ld-panel-content -->

</div> <!-- .ld-panel -->
