<ul class="ld-nav">
    <li><a href="<?php echo $this->admin->getUrl() ?>"><?php echo $this->translate("Back home") ?></a></li>
</ul>

<h2><?php echo $this->translate("Add an application") ?></h2>

<?php if (empty($this->package)) : ?>

<ul class="blocks mini new-instance">
    <?php
    foreach ($this->packages as $id => $package) {
        if ($package->id == 'admin') {
            continue;
        }
        $inlineStyle = '';
        if ($icon = $package->icon) {
            $inlineStyle .= "background-image:url($icon);";
        }
        $url = $this->url(array('controller' => 'instance', 'action' => 'new', 'site' => $this->site->id)) . '?packageId=' . $id;
        printf('<li class="%s" style="%s"><a href="%s">%s</a><br/><span class="description">%s</span></li>' . "\n",
            $id, $inlineStyle, $url, $package->name, $package->description);
    }
    ?>
</ul>

<p><?php echo $this->translate("You can also:") ?></p>

<ul>
<li><a href="<?php echo $this->url(array('controller' => 'instance', 'action' => 'clone')) ?>">
    <?php echo $this->translate("Clone an application from a backup") ?>
</a></li>
</ul>

<?php else : ?>

<div class="ld-panel-content h6e-block no-tab">

<h3><?php echo sprintf($this->translate("Install %s"), '<strong>' . $this->escape($this->package->name) . '</strong>') ?></h3>

<form method="post" action="">

    <?php $this->preferencesRenderer($this->preferences, array(), 'preferences'); ?>

    <input type="hidden" name="packageId" value="<?php echo $this->escape($this->package->id) ?>"/>
    <input type="submit" class="submit button ld-button" value="<?php echo $this->translate("Install") ?>"/>

</form>

</div>

<?php endif ?>
