<?php if (empty($this->package)) : ?>
    
<h2><?php echo $this->translate("Add a new application") ?></h2>

<ul class="blocks mini new-instance">
    <?php
    foreach ($this->packages as $id => $package) {
        if ($package->id == 'admin') {
            continue;
        }
        $url = $this->url(array('controller' => 'instance', 'action' => 'new', 'site' => $this->site->id)) . '?packageId=' . $id;
        printf("<li class='" . $id . "'><a href=\"%s\">%s</a></li>", $url, $package->name);
    }
    ?>
</ul>

<p><?php echo $this->translate("You can also:") ?></p>

<ul>
<li><a href="<?php echo $this->url(array('controller' => 'instance', 'action' => 'clone')) ?>">
    <?php echo $this->translate("Clone an application from a backup") ?>
</a></li>
</ul>

<?php else : ?>

<h2><?php echo sprintf($this->translate("Add a new '%s'"), $this->escape($this->package->name)) ?></h2>

<form method="post" action="">

    <?php $this->preferencesRenderer($this->preferences, array(), 'preferences'); ?>

    <input type="hidden" name="packageId" value="<?php echo $this->escape($this->package->id) ?>"/>
    <input type="submit" class="submit button ld-button" value="<?php echo $this->translate("Create") ?>"/>

</form>

<?php endif ?>