<?php $this->instancesList(false) ?>

<div class="ld-panel">

<?php $this->instanceNavigation() ?>

<div class="ld-panel-content">

<?php if (isset($this->supported) && $this->supported == false) : ?>

    <p><?php echo $this->translate('Not supported.') ?></p>

<?php elseif (empty($this->users)) : ?>

    <p><?php echo $this->translate('No user available.') ?></p>

<?php else : ?>

<form action="<?php echo $this->url() ?>" method="post">

<table class="h6e-data">

    <tr>
        <th><?php echo $this->translate('Username') ?></th>
        <th><?php echo $this->translate('Full Name') ?></th>
        <th><?php echo $this->translate('Role') ?></th>
    </tr>

<?php foreach ($this->users as $user) : ?>

    <tr>
        <td><?php echo $user['username'] ?></td>
        <td><?php echo $user['fullname'] ?></td>
        <td>
            <select name="roles[<?php echo $user['username'] ?>]">
                <?php foreach ($this->roles as $role) : ?>
                    <?php
                    $username = $user['username'];
                    $selected = isset($this->userRoles[$username]) && $this->userRoles[$username] == $role ?
                        'selected="selected"' : '';
                    ?>
                    <option <?php echo $selected ?> value="<?php echo $role ?>"><?php echo ucfirst($role) ?></option>
                <?php endforeach ?>
            </select>
        </td>
    </tr>

<?php endforeach ?>

</table>

<input type="submit" class="submit button" value="<?php echo $this->translate('Update') ?>"/>

</form>

<?php endif ?>

</div> <!-- .ld-panel-content -->

</div> <!-- .ld-panel -->
