<?php $this->instancesList(false) ?>

<div class="ld-panel">

<?php $this->instanceNavigation() ?>

<div class="ld-panel-content">

<table class="h6e-data">
    <tr>
        <th>package</th>
        <th>type</th>
        <th>version</th>
        <th>status</th>
        <th>action</th>
    </tr>
    <tbody>
    <tr>
        <td><?php echo $this->instance->getPackageId() ?></td>
        <td><?php echo $this->instance->getType() ?></td>
        <td><?php echo $this->instance->getVersion() ?></td>
        <td><?php echo ($this->instance->hasUpdate = $this->instance->hasUpdate()) ? 'Need update' : 'Up to date' ?></td>
        <td>
        <?php if ($this->instance->hasUpdate) : ?>
            <a href="<?php echo $this->instanceActionUrl('update') ?>?version=<?php echo $this->instance->hasUpdate ?>">update</a>
        <?php endif ?>
        </td>
    </tr>
    </tbody>
    <?php if (count($this->extensions) > 0) : ?>
        <tr class="th2"><th colspan="5"><em>Extensions</em></th></tr>
        <tbody>
        <?php foreach($this->extensions as $extension) : ?>
            <tr>
                <td><?php echo $extension->getPackageId() ?></td>
                <td><?php echo $extension->getType() ?></td>
                <td><?php echo $extension->getVersion() ?></td>
                <td><?php echo $extension->hasUpdate ? 'Need update' : 'Up to date' ?></td>
                <td>
                    <?php if ($extension->hasUpdate) : ?>
                        <a href="<?php echo $this->instanceActionUrl('extensions') . '?update=' . $extension->getPath() ?>">update</a>
                    <?php endif ?>
                    <a href="<?php echo $this->instanceActionUrl('extensions') . '?remove=' . $extension->getPath() ?>">remove</a>
                </td>
            </tr>
        <?php endforeach ?>
        </tbody>
    <?php endif ?>
</table>

<p>You can also:</p>

<ul>
    <li><a href="<?php echo $this->instanceActionUrl('delete') ?>">Delete this application</a></li>
</ul>

</div> <!-- .ld-panel-content -->

</div> <!-- .ld-panel -->
