<?php $this->instancesList(false) ?>

<div class="ld-panel">

<?php $this->instanceNavigation() ?>

<div class="ld-panel-content">

<table class="h6e-data">
    <tr>
        <th><?php echo $this->translate('Package') ?></th>
        <th><?php echo $this->translate('Type') ?></th>
        <th><?php echo $this->translate('Version') ?></th>
        <th><?php echo $this->translate('Status') ?></th>
        <th colspan="2"><?php echo $this->translate('Actions') ?></th>
    </tr>
    <tbody>
    <tr>
        <td><?php echo $this->instance->getPackageId() ?></td>
        <td><?php echo $this->instance->getType() ?></td>
        <td><?php echo $this->instance->getVersion() ?></td>
        <td><?php echo ($this->instance->hasUpdate = $this->instance->hasUpdate()) ?
            $this->translate('update available') : $this->translate('up to date') ?></td>
        <td>
        <?php if ($this->instance->hasUpdate) : ?>
            <a href="<?php echo $this->instanceActionUrl('update') ?>?version=<?php echo $this->instance->hasUpdate ?>"><?php
                echo $this->translate('update')
            ?></a>
        <?php endif ?>
        </td>
        <td></td>
    </tr>
    </tbody>
    <?php if (count($this->extensions) > 0) : ?>
        <tr class="th2"><th colspan="6"><em>Extensions</em></th></tr>
        <tbody>
        <?php foreach($this->extensions as $extension) : ?>
            <tr>
                <td><?php echo $extension->getPackageId() ?></td>
                <td><?php echo $extension->getType() ?></td>
                <td><?php echo $extension->getVersion() ?></td>
                <td><?php echo $extension->hasUpdate ?
                    $this->translate('update available') : $this->translate('up to date') ?></td>
                <td>
                    <?php if ($extension->hasUpdate) : ?>
                        <a href="<?php echo $this->instanceActionUrl('extensions') . '?update=' . $extension->getPath() ?>"><?php
                            echo $this->translate('update')
                        ?></a>
                    <?php endif ?>
                </td>
                <td>
                    <a href="<?php echo $this->instanceActionUrl('extensions') . '?remove=' . $extension->getPath() ?>"><?php
                        echo $this->translate('uninstall')
                    ?></a>
                </td>
            </tr>
        <?php endforeach ?>
        </tbody>
    <?php endif ?>
</table>

<p><?php echo $this->translate('You can also:') ?></p>

<ul>
    <li><a href="<?php echo $this->instanceActionUrl('delete') ?>"><?php echo $this->translate('Delete this application') ?></a></li>
</ul>

</div> <!-- .ld-panel-content -->

</div> <!-- .ld-panel -->
