<?php $this->instancesList(false) ?>

<div class="ld-panel">

<?php $this->instanceNavigation() ?>

<div class="ld-panel-content">

<div id="available-themes">

    <form id="available-themes" method="post" action="<?php echo $this->url() ?>">

        <?php if (!empty($this->themes)) : ?>

            <h3><?php echo $this->translate('Available Themes') ?></h3>

            <div class="themes-container">
            
            <div class="themes">

                <?php foreach($this->themes as $id => $theme) : ?>

                    <?php $screenshot = isset($theme['screenshot']) ?
                        $theme['screenshot'] : 'http://h6e.net/releases/wp-minimal-screenshot.png' ?>

                    <div class="theme">
                    <label for="theme-<?php echo $id ?>">
                    <img src="<?php echo $screenshot ?>" width="150" height="112" alt="" />
                    <input id="theme-<?php echo $id ?>" <?php echo ($theme['active'] ? 'checked="checked"' : '') ?>
                        type="radio" name="theme" value="<?php echo $id ?>" />
                    <?php echo $theme['name'] ?>
                    </label>
                    </div>

                <?php endforeach ?>

            </div>

            </div>

            <div style="margin:1em 0">
                <input type="hidden" name="referer" value=""/>
                <input type="submit" class="submit button" value="<?php echo $this->translate('Update') ?>"/>
            </div>

        <?php else: ?>

            <p><?php echo $this->translate('No theme available for this application.') ?></p>

        <?php endif ?>

    </form>

</div>

<div id="themes-preferences">

    <?php if (!empty($this->preferences)) : ?>

        <h3><?php echo $this->translate('Theme Preferences') ?></h3>

        <form method="post" action="">

            <?php $this->preferencesRenderer($this->preferences, $this->configuration, 'configuration'); ?>

            <div style="margin-bottom:2em">
            <input type="submit" class="submit button" value="<?php echo $this->translate('Update') ?>"/>
            </div>

        </form>

    <?php endif ?>

</div>

</div> <!-- .ld-panel-content -->

</div> <!-- .ld-panel -->
