<?php $this->instanceWidget() ?>

<div class="ld-panel">

<?php $this->instanceNavigation() ?>

<div class="ld-panel-content h6e-block">

<div id="available-themes">

    <form id="available-themes" method="post" action="<?php echo $this->url() ?>">

        <?php if (!empty($this->themes)) : ?>

            <h3><?php echo $this->translate('Available Themes') ?></h3>

            <div class="themes-container">

            <div class="themes">

                <?php foreach ($this->themes as $id => $theme) : ?>

                    <div class="theme">
                    <label for="theme-<?php echo $id ?>">
                    <?php if (isset($theme['screenshot'])) : ?>
                        <img src="<?php echo $theme['screenshot'] ?>" width="150" height="112" alt="" />
                    <?php else : ?>
                        <div class="no-theme-screenshot"></div>
                    <?php endif ?>
                    <input id="theme-<?php echo $id ?>" <?php echo ($theme['active'] ? 'checked="checked"' : '') ?>
                        type="radio" name="theme" value="<?php echo $id ?>" />
                    <?php echo $theme['name'] ?>
                    </label>
                    </div>

                <?php endforeach ?>

                <?php foreach ($this->availableThemes as $id => $package) : ?>

                    <?php if ($this->instance->hasExtension($id)) continue ?>

                    <div class="theme">
                    <label for="theme-<?php echo $id ?>">
                    <div class="no-theme-screenshot"></div>
                    <input id="theme-<?php echo $id ?>" disabled="disabled" type="radio" />
                    <?php echo $package->getName() ?>
                    |
                    <a href="<?php echo $this->instanceActionUrl('extensions') . '?add=' . $id ?>">Install</a>
                    </label>
                    </div>

                <?php endforeach ?>

            </div>

            </div>

        <?php else: ?>

            <p><?php echo $this->translate('No theme available for this application.') ?></p>

        <?php endif ?>

        <?php if (!empty($this->preferences)) : ?>

        <div id="themes-preferences">
                <h3><?php echo $this->translate('Theme Preferences') ?></h3>
                <?php $this->preferencesRenderer($this->preferences, $this->configuration, 'configuration'); ?>
        </div>

        <?php endif ?>

        <input type="hidden" name="referer" value=""/>
        <input type="submit" class="submit button" value="<?php echo $this->translate('Update') ?>"/>

    </form>

</div>

</div> <!-- .ld-panel-content -->

</div> <!-- .ld-panel -->
