<?php
$site = Zend_Registry::get('site');
$this->js()->append('/jquery/jquery.js', 'js-jquery');
$this->js()->append('/jquery/jquery-ui.js', 'js-jquery-ui');
$this->js()->append('/ld/ld.js', 'admin');
$authUrl = $this->url(array(
    'module' => 'identity', 'controller' => 'openid', 'action' => 'auth'), 'default', false);
$this->headLink(array('rel' => 'openid2.provider', 'href' => Zend_OpenId::absoluteURL($authUrl)));
?>
<?php echo $this->doctype('XHTML1_STRICT') . "\n" ?>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<?php echo $this->headTitle() . "\n" ?>
<?php echo '<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>' . "\n"  ?>
<?php echo $this->headLink() . "\n" ?>
<?php echo $this->headStyle() . "\n" ?>
<?php echo $this->headScript() . "\n" ?>
</head>
<body class="ld-layout">

<?php Ld_Ui::top_bar(); ?>

<div class="h6e-main-content">

  <?php $bc = $this->navigation()->breadcrumbs()->__toString(); ?>

  <?php if (!empty($bc)) : ?>
  <div class="h6e-bread-crumbs">
      <?php echo $bc ?>
  </div>
  <?php endif ?>

  <div class="h6e-page-content">
      <?php echo $this->layout()->content ?>
  </div>

  <div class="h6e-simple-footer">
          <?php
          printf(
              $this->translate('Powered by <a href="%s">La Distribution</a>, a community project initiated by <a href="%s">h6e</a>.'),
              'http://ladistribution.net/', 'http://h6e.net/' );
          ?>
          <form class="inline" action="" method="post" id="ld-lang-switcher">
              <label><?php echo $this->translate("Language:") ?></label>
              <select name="ld-lang">
                  <?php
                  $locales = array_merge(array('auto' => 'auto'), $site->getLocales());
                  foreach ($locales as $id => $label) {
                      if (isset($_COOKIE['ld-lang']) && $id == $_COOKIE['ld-lang']) {
                          echo "<option selected=\"selected\" value=\"$id\">$label</option>\n";
                      } else {
                          echo "<option value=\"$id\">$label</option>\n";
                      }
                  }
                  ?>
               </select>
               <input type="submit" class="submit" value="Ok"/>
          </form>
  </div>

</div>

<?php Ld_Ui::super_bar(array('jquery' => false, 'ld-js' => false)); ?>

<script type="text/javascript">
(function($) {
    $(document).ready(function($){
        if(Ld) Ld.init($);
    });
})(jQuery);
</script>

</body>
</html>