<?php

if (isset($this->admin)) {
    $this->headLink(array('rel' => 'openid2.provider', 'href' => $this->admin->getOpenidAuthUrl()));
}

echo $this->doctype('XHTML5') . "\n"

?>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<?php echo $this->headTitle()->setIndent(2) . "\n" ?>
<?php echo '  <meta charset="utf-8"/>' . "\n"  ?>
<?php echo '  <meta name="viewport" content="width=device-width, initial-scale=1.0"/>' . "\n"  ?>
<?php if (isset($this->noIndex)) echo '  <meta name="robots" content="noindex"/>' . "\n"  ?>
<?php echo $this->headLink()->setIndent(2) . "\n" ?>
<?php echo $this->headScript()->setIndent(2) . "\n" ?>
<?php echo $this->headStyle() ?>
</head>
<body class="ld-layout h6e-layout <?php if (isset($this->bodyClass)) echo $this->bodyClass ?>">

<?php Ld_Ui::topBar(); ?>

<div class="ld-main-content h6e-main-content">

  <?php $bc = $this->navigation()->breadcrumbs()->__toString() ?>

  <?php if (!defined('LD_BREADCRUMBS') || constant('LD_BREADCRUMBS')) : ?>
  <?php if (!empty($bc)) : ?>
  <div class="h6e-bread-crumbs">
      <?php echo $bc ?>
  </div>
  <?php endif ?>
  <?php endif ?>

  <?php if (isset($this->layoutTitle)) : ?>
      <h1 class="h6e-page-title"><?php echo $this->layoutTitle ?></h1>
  <?php endif ?>

  <?php if (isset($this->menu)) : ?>
      <?php echo $this->menu($this->menu)->renderMenu(null, array('ulClass' => 'h6e-tabs', 'maxDepth' => 1)); ?>
  <?php endif ?>

  <div class="h6e-page-content">
      <?php echo $this->layout()->content ?>
  </div>

  <div class="h6e-simple-footer">
          <?php
          $text = sprintf(
              $this->translate('Powered by <a href="%s">La Distribution</a>, a community project initiated by <a href="%s">h6e</a>.'),
              'http://ladistribution.net/', 'http://h6e.net/' );
          echo Ld_Plugin::applyFilters('Admin:footerText', $text);
          ?>
          <form class="inline" action="" method="post" id="ld-lang-switcher">
              <label><?php echo $this->translate("Language:") ?></label>
              <select name="ld-lang">
                  <?php
                  $site = Zend_Registry::get('site');
                  $locales = array_merge(array('auto' => 'auto'), $site->getLocales());
                  foreach ($locales as $id => $label) {
                      if (isset($_COOKIE['ld-lang']) && $id == $_COOKIE['ld-lang']) {
                          echo "<option selected=\"selected\" value=\"$id\">$label</option>\n";
                      } else {
                          echo "<option value=\"$id\">$label</option>\n";
                      }
                  }
                  ?>
               </select>
               <input type="submit" class="submit" value="Ok"/>
          </form>
  </div>

</div>

<?php Ld_Plugin::doAction('Layout:end') ?>

</body>
</html>