<div id="ld-login">

  <div id="ld-login-box">

    <h2><?php echo $this->translate("Log In") ?></h2>

    <?php
    if (isset($this->authentication)) {
        switch ($this->authentication->getCode()) {
            case Zend_Auth_Result::SUCCESS:
                // everything OK
                break;
            case Zend_Auth_Result::FAILURE_IDENTITY_NOT_FOUND:
                echo '<div class="ld-error"><b>' . $this->translate("Error:") . '</b> ' . $this->translate("Invalid username.") . '</div>';
                break;
            case Zend_Auth_Result::FAILURE_CREDENTIAL_INVALID:
                echo '<div class="ld-error"><b>' . $this->translate("Error:") . '</b> ' . $this->translate("Incorrect password.") . '</div>';
                break;
            default:
                $messages = $this->authentication->getMessages();
                foreach ($messages as $message)
                    echo '<div class="ld-error"><b>' . $this->translate("Error:") . '</b> ' . $this->escape($message) . '</div>';
                break;
        }
    }
    ?>

    <form method="post" action="">

        <?php if (isset($this->ld_auth_user)) : ?>

            <div style="display:none">

            <label for="ld-auth-username"><?php echo $this->translate("Username (or OpenID):") ?></label>
            <input id="ld-auth-username" class="text" type="text" name="openid_identifier" value="<?php echo $this->ld_auth_user['username'] ?>"/>

            </div>

            <label for="ld-auth-password"><?php echo $this->translate("Password:") ?></label>
            <input id="ld-auth-password" class="text"  type="password" name="ld_auth_password" value=""/>

            <label for="ld-auth-remember">
                <input id="ld-auth-remember" type="checkbox" name="ld_auth_remember"/>
                <?php echo $this->translate("Remember me") ?>
            </label>

            <script type="text/javascript">jQuery('#ld-auth-password').focus();</script>

        <?php else : ?>

            <label for="ld-auth-username"><?php echo $this->translate("Username (or OpenID):") ?></label>
            <input id="ld-auth-username" class="text" type="text" name="openid_identifier" value=""/>

            <script type="text/javascript">jQuery('#ld-auth-username').focus();</script>

        <?php endif ?>

        <?php foreach ($this->postParams as $key => $value) : ?>
            <input type="hidden" name="<?php echo $key ?>" value="<?php echo $this->escape($value) ?>"/>
        <?php endforeach ?>

        <input type="hidden" name="ld_auth_action" value="login"/>

        <?php if (isset($this->referer)) : ?>
            <input type="hidden" name="ld_referer" value="<?php echo $this->escape($this->referer) ?>"/>
        <?php endif ?>

        <input type="hidden" name="openid_action" value="login"/>
        <input class="button" type="submit" value="<?php echo $this->translate("Log In") ?>"/>

    </form>

    <div style="display:none">

    <h2>OpenID</h2>

    <form method="post" action="">
        <label>OpenID URL</label><br />
        <input type="text" name="openid_identifier" value=""/>
        <br />
        <input type="hidden" name="openid_action" value="login"/>
        <input class="button" type="submit" value="Connect"/>
    </form>

    </div>

    <div class="links">
      <?php if ($this->open_registration) : ?>
      <a href="<?php echo $this->url(array('module' => 'default', 'action' => 'register', 'controller' => 'auth')); ?>"><?php echo $this->translate("Register") ?></a>
      <?php endif ?>
    </div>

  </div>

</div>
