<div id="ld-login">

  <div id="ld-login-box">

    <h2><?php echo $this->translate("Log In") ?></h2>

    <?php
    if (isset($this->authentication)) {
        switch ($this->authentication->getCode()) {
            case Zend_Auth_Result::SUCCESS:
                // everything OK
                break;
            case Zend_Auth_Result::FAILURE_IDENTITY_NOT_FOUND:
                echo '<div class="ld-error"><b>' . $this->translate("Error:") . '</b> ' . $this->translate("Invalid username.") . '</div>';
                break;
            case Zend_Auth_Result::FAILURE_CREDENTIAL_INVALID:
                echo '<div class="ld-error"><b>' . $this->translate("Error:") . '</b> ' . $this->translate("Incorrect password.") . '</div>';
                break;
            default:
                $messages = $this->authentication->getMessages();
                foreach ($messages as $message)
                    echo '<div class="ld-error"><b>' . $this->translate("Error:") . '</b> ' . $this->escape($message) . '</div>';
                break;
        }
    }
    ?>

    <form id="ld-auth-form" method="post" action="">

        <?php if (isset($this->ld_auth_user)) : ?>

            <div style="display:none">

            <label for="ld-auth-username"><?php echo $this->translate("Username (or OpenID):") ?></label>
            <input id="ld-auth-username" class="text" type="text" name="openid_identifier" value="<?php echo $this->ld_auth_user['username'] ?>"/>

            </div>

            <label for="ld-auth-password"><?php echo $this->translate("Password:") ?></label>
            <input id="ld-auth-password" class="text"  type="password" name="ld_auth_password" value=""/>

            <label for="ld-auth-remember">
                <input id="ld-auth-remember" type="checkbox" name="ld_auth_remember"/>
                <?php echo $this->translate("Remember me") ?>
            </label>

            <script type="text/javascript">jQuery('#ld-auth-password').focus();</script>

        <?php else : ?>

            <?php
            if (empty($_GET['another-identity'])) {
                $identities = $this->identities;
            }
            ?>

            <label for="ld-auth-username"><?php echo $this->translate("Username (or OpenID):") ?></label>
            <input id="ld-auth-username" class="text" type="text" name="openid_identifier" value=""/>

            <script type="text/javascript">jQuery('#ld-auth-username').focus();</script>

            <div id="ld-identities" style="display:none">
                <?php
                foreach ($identities as $identity => $user) :
                ?>
                <a href="#">
                    <?php echo Ld_Ui::getAvatar($user, 32) ?>
                    <?php $displayname = empty($user['fullname']) ? $user['username'] : $user['username']; ?>
                    <span class="fullname"><?php echo $displayname ?></span>
                    <br>
                    <span class="identity"><?php echo $identity ?></span>
                </a>
                <?php endforeach ?>
            </div>

        <?php endif ?>

        <?php foreach ($this->postParams as $key => $value) : ?>
            <input type="hidden" name="<?php echo $key ?>" value="<?php echo $this->escape($value) ?>"/>
        <?php endforeach ?>

        <input type="hidden" name="ld_auth_action" value="login"/>

        <?php if (isset($this->referer)) : ?>
            <input type="hidden" name="ld_referer" value="<?php echo $this->escape($this->referer) ?>"/>
        <?php endif ?>

        <input type="hidden" name="openid_action" value="login"/>
        <input id="ld-auth-login" class="button" type="submit" value="<?php echo $this->translate("Log In") ?>"/>

    </form>

    <div class="links">
      <a id="ld-auth-another-identity-link" style="display:none" href="?another-identity=1"><?php echo $this->translate("Log In with another identity") ?></a>
      <?php if ($this->open_registration && empty($this->ld_auth_user)) : ?>
          <a id="ld-auth-register-link" href="<?php echo $this->url(array('module' => 'default', 'action' => 'register', 'controller' => 'auth')); ?>"><?php echo $this->translate("Register") ?></a>
      <?php endif ?>
    </div>

  </div>

</div>

<?php if (!empty($identities)) : ?>
    <script type="text/javascript">
    jQuery(document).ready(function($){
        $('#ld-auth-username, label[for="ld-auth-username"], #ld-auth-login, #ld-auth-register-link').hide();
        $('#ld-identities, #ld-auth-another-identity-link').show();
        $('#ld-identities a').click(function() {
            $('#ld-auth-username').val( $(this).children('span.identity').text() );
            $('#ld-auth-form').submit();
            return false;
        });
    });
    </script>
<?php endif ?>
