<div id="ld-login">

  <div id="ld-login-box">

    <?php if (isset($this->token)) : ?>
        <h2><?php echo $this->translate("Password Update") ?></h2>
    <?php else : ?>
        <h2><?php echo $this->translate("Password Lost") ?></h2>
    <?php endif ?>

    <?php
    if (isset($this->error)) {
        if (is_string($this->error)) {
            echo '<div class="ld-error"><b>' . $this->translate("Error:") . '</b> ' . $this->escape($this->error) . '</div>';
        }
    }
    ?>

    <form method="post" action="">

        <?php if (isset($this->sent)) : ?>

            <p><?php echo $this->translate("An email has been sent to you.") ?></p>

        <?php elseif (isset($this->fertig)) : ?>

            <p><?php echo $this->translate('Congratulations! Your password has been updated.') ?></p>

            <p><?php echo '<a href="' . Ld_Ui::getAdminUrl() . '">' . $this->translate("Continue") . '</a>.' ?></p>

        <?php elseif (isset($this->token)) : ?>

            <p><?php echo $this->translate("You're about to finish the password reset procedure. Please now submit your new password.") ?></p>

            <label for="ld-reset-password"><?php echo $this->translate("New Password:") ?></label>
            <input id="ld-reset-password" class="text"  type="password" name="ld_reset_password" value="" autocomplete="off"/>

            <label for="ld-reset-password-again"><?php echo $this->translate("New Password again:") ?></label>
            <input id="ld-reset-password-again" class="text" type="password" name="ld_reset_password_again" value="" autocomplete="off"/>

            <input class="submit button ld-button" type="submit" value="<?php echo $this->translate("Update my password") ?>"/>

        <?php else : ?>

            <label for="ld-auth-username"><?php echo $this->translate("Username (or Email):") ?></label>
            <input id="ld-auth-username" class="text" type="text" name="openid_identifier" value=""/>

            <p><?php echo $this->translate("An email will be sent with instructions on how to reset your password.") ?></p>

            <input class="submit button ld-button" type="submit" value="<?php echo $this->translate("Reset my password") ?>"/>

        <?php endif ?>

    </form>

  </div>

</div>
