<div id="ld-login">

  <div id="ld-login-box">
      
    <?php if (isset($this->complete) || isset($this->finish)) : ?>
        <h2><?php echo $this->translate("Complete Registration") ?></h2>
    <?php else : ?>
        <h2><?php echo $this->translate("Register") ?></h2>
    <?php endif ?>

    <?php

    if (isset($this->error)) {
        if (is_string($this->error)) {
            echo '<div class="ld-error"><b>' . $this->translate("Error:") . '</b> ' . $this->escape($this->error) . '</div>';
        }
    }

    ?>

    <form method="post" action="">

        <label for="ld-register-username"><?php echo $this->translate("Username:") ?></label>
        <?php if (FALSE && isset($this->finish, $this->user, $this->user['username'])) : ?>
            <span class="text"><?php echo $this->escape($this->user['username']); ?></span>
        <?php else : ?>
            <input id="ld-register-username" class="text" type="text" name="ld_register_username" value="<?php
                if (isset($this->user, $this->user['username'])) echo $this->escape($this->user['username']);
            ?>"/>
        <?php endif ?>

        <label for="ld-register-fullname"><?php echo $this->translate("Full Name:") ?></label>
        <?php if (FALSE && isset($this->finish, $this->user, $this->user['fullname'])) : ?>
            <span class="text"><?php echo $this->escape($this->user['fullname']); ?></span>
        <?php else : ?>
            <input id="ld-register-fullname" class="text" type="text" name="ld_register_fullname" value="<?php
                if (isset($this->user, $this->user['fullname'])) echo $this->escape($this->user['fullname']);
            ?>"/>
        <?php endif ?>

        <label for="ld-register-email"><?php echo $this->translate("Email:") ?></label>
        <?php if (FALSE && isset($this->finish, $this->user, $this->user['email'])) : ?>
            <span class="text"><?php echo $this->escape($this->user['email']); ?></span>
        <?php else : ?>
            <input id="ld-register-email" class="text" type="text" name="ld_register_email" value="<?php
                if (isset($this->user, $this->user['email'])) echo $this->escape($this->user['email']);
            ?>"/>
        <?php endif ?>

        <label for="ld-register-password"><?php echo $this->translate("Password:") ?></label>
        <input id="ld-register-password" class="text"  type="password" name="ld_register_password" value="" autocomplete="off"/>

        <label for="ld-register-password-again"><?php echo $this->translate("Password again:") ?></label>
        <input id="ld-register-password-again" class="text" type="password" name="ld_register_password_again" value="" autocomplete="off"/>

        <?php if (isset($this->referer)) : ?>
            <input type="hidden" name="ld_referer" value="<?php echo $this->escape($this->referer) ?>"/>
        <?php endif ?>

        <input type="hidden" name="ld_auth_action" value="register"/>

        <?php Ld_Plugin::doAction('Auth:register:form'); ?>

        <input class="submit button ld-button" type="submit" value="<?php echo $this->translate("Register") ?>"/>

    </form>

  </div>

</div>
