<h2><?php echo $this->translate("Settings") ?></h2>

<div class="ld-panel">

<?php $this->partialNavigationMenu('Settings') ?>

<div class="ld-panel-content h6e-block">

    <h3><?php echo $this->translate("Colors") ?></h3>

    <form action="" method="post">

        <?php
        $parameters = array('colorSchemes' => array('base', 'bars', 'panels'), 'colors' => $this->colors);
        echo $this->partial('partials/color-schemes.phtml', $parameters);
        ?>

        <input type="submit" class="submit button ld-button" value="<?php echo $this->translate("Update") ?>"/>

    </form>

</div>

</script>

</div>