<h2><?php echo $this->translate("Plugins") ?></h2>

<form action="<?php echo $this->url() ?>" method="post">
    
<table id="plugins" class="h6e-data">
<tr>
    <th><?php echo $this->translate("Name") ?></th>
    <th><?php echo $this->translate("Description") ?></type>
    <th><?php echo $this->translate("Version") ?></type>
    <th colspan="2"><?php echo $this->translate("Actions") ?></th>
</tr>
<tbody>
<?php
foreach ($this->plugins as $id => $plugin) {
    ?>
    <tr id="<?php echo $id ?>">
        <td><?php echo $plugin['name'] ?></td>
        <td><?php echo $plugin['description'] ?></td>
        <td><?php echo $plugin['version'] ?></td>
        <td>
            <label>
            <input type="radio" name="plugins[<?php echo $id ?>]" value="active"
                <?php if ($plugin['active']) echo 'checked="checked"' ?>/>
                <?php echo $this->translate("Active") ?></label>
            <label>
            <input type="radio" name="plugins[<?php echo $id ?>]" value="inactive"
                <?php if (!$plugin['active']) echo 'checked="checked"' ?>/>
                <?php echo $this->translate("Inactive") ?></label>
        </td>
    </tr>
    <?php
}
?>
</tbody>
</table>

<input type="submit" class="submit button" value="<?php echo $this->translate("Update") ?>"/>

</form>