<h2><?php echo $this->translate("Plugins") ?></h2>

<div class="ld-panel">

<?php $this->partialNavigationMenu('Settings') ?>

<div class="ld-panel-content">

<form action="<?php echo $this->url() ?>" method="post">
    
<table id="plugins" class="h6e-data">
<tbody>
<?php
foreach ($this->plugins as $id => $plugin) {
    $infos = $plugin->infos();
    ?>
    <tr>
        <th><?php echo $infos['name'] ?></th>
        <th class="plugin-description"><?php echo $infos['description'] ?></th>
        <th class="plugin-active">
            <label>
            <input type="radio" name="plugins[<?php echo $id ?>]" value="active"
                <?php if ($plugin->active) echo 'checked="checked"' ?>/>
                <?php echo $this->translate("Active") ?></label>
            <label>
            <input type="radio" name="plugins[<?php echo $id ?>]" value="inactive"
                <?php if (!$plugin->active) echo 'checked="checked"' ?>/>
                <?php echo $this->translate("Inactive") ?></label>
        </th>
    </tr>
    <?php if ($plugin->active && (method_exists($plugin, 'preferences') || method_exists($plugin, 'status'))) : ?>
        <tr>
            <td></td>
            <td colspan="2" class="plugin-details">
                <?php if (method_exists($plugin, 'preferences')) : ?>
                    <?php $this->preferencesRenderer($plugin->preferences(), $this->configuration, 'configuration'); ?>
                <?php endif ?>
                <?php if (method_exists($plugin, 'status') && $status = $plugin->status()) : ?>
                    <p class="plugin-status <?php echo $status[0] == 0 ? 'error' : 'ok' ?>"><strong><?php echo $status[1] ?></strong></p>
                <?php endif ?>
            </td>
        </tr>
    <?php else: ?>
        <tr style="display:none"></tr>
    <?php endif ?>
    <?php
}
?>
</tbody>
</table>

<input type="submit" class="submit button" value="<?php echo $this->translate("Update") ?>"/>

</form>

<script type="text/javascript">
Ld.dataTables = function($)
{
    $(".h6e-data tbody").each(function() {
        $(this).children('tr').each(function(i) {
            if (i % 4 == 2) $(this).addClass('th2');
        });
    })
}
</script>

</div>

</div>