<h2><?php echo $this->translate("Repositories") ?></h2>

<div class="ld-panel">

<?php $this->partialNavigationMenu('Ressources') ?>

<div class="ld-panel-content">

<p><?php echo $this->translate("Are you sure you want to remove this repository?") ?></p>

<form method="post" action="">
    
    <input type="hidden" name="id" value="<?php echo $this->escape($this->repository->id) ?>"/>
    <input type="submit" class="submit button ld-button" value="<?php echo $this->translate("Remove") ?>"/>

</form>

</div>

</div>
