<h2><?php echo $this->translate("Settings") ?></h2>

<div class="ld-panel">

<?php $this->partialNavigationMenu('Settings') ?>

<div class="ld-panel-content h6e-block">

<h3><?php echo $this->translate("Repositories") ?></h3>

<?php echo $this->partial('repositories/list.phtml', array('repositories' => $this->repositories)); ?>

<h3><?php echo $this->translate("You can:") ?></h3>

<ul>
    <li><a href="<?php echo $this->url(array('action' => 'new', 'type' => 'local')) ?>">
        <?php echo $this->translate("Create a local repository") ?>
    </a></li>
    <li><a href="<?php echo $this->url(array('action' => 'new', 'type' => 'remote')) ?>">
        <?php echo $this->translate("Add a remote repository") ?>
    </a></li>
</ul>

</div>

</div>