<?php if (empty($this->repositories) || count($this->repositories) == 0) : ?>
    
    <p>None</p>
    
<?php else : ?>

    <?php
    $this->js()->append('/jquery/jquery.tablednd.js', 'js-jquery-tablednd', 'ld-js-jquery-ui-tablednd');
    ?>

    <table id="repositories" class="h6e-data">
    <tr>
        <th></th>
        <th><?php echo $this->translate("URL") ?></th>
        <th><?php echo $this->translate("Type") ?></type>
        <th colspan="2"><?php echo $this->translate("Actions") ?></th>
    </tr>
    <tbody>
    <?php
    foreach ($this->repositories as $id => $repository) {
        $manageUrl = $this->url(array('id' => $id, 'action' => 'manage'));
        $removeUrl = $this->url(array('id' => $id, 'action' => 'delete'));
        ?>
        <tr id="<?php echo $id ?>">
            <td class="move"></td>
            <td><?php echo $repository->getUrl() ?></td>
            <td><?php echo $repository->type ?></td>
            <td><a href="<?php echo $manageUrl ?>"><?php echo $repository->type == 'local' ?
                $this->translate('manage') : $this->translate('browse') ?></a></td>
            <td><a href="<?php echo $removeUrl ?>"><?php echo $this->translate("remove") ?></a></td>
        </tr>
        <?php
    }
    ?>
    </tbody>
    </table>

    <script type="text/javascript">
    (function($) {
        $(document).ready(function() {
            $("#repositories").tableDnD({
                onDragClass: "dragging",
                onDrop: function(table, row) {
                    $.post("<?php echo $this->url(array('action' => 'order')) ?>", $("#repositories").tableDnDSerialize());
                    $("#repositories tr").removeClass('even');
                    $("#repositories tr:even").addClass('even');
                },
            });
        });
    })(jQuery);
    </script>

<?php endif ?>
