<h2>Manage repository</h2>

<p><strong>Repository URL:</strong> <?php echo $this->repository->getUrl() ?></p>

<h3>Upload a new package</h3>

<p>Zip file please.</p>

<form method="post" enctype="multipart/form-data" action="">
    <p>
        <input type="file" name="file"/>
        <input name="upload" class="submit" type="submit" value="Upload"/>
    </p>
</form>

<h3>Packages</h3>

<?php require('repository.phtml') ?>

<h3>Actions</h3>

<ul>
    <li>
        <a href="<?php echo $this->url(array('controller' => 'repositories', 'action' => 'delete', 'id' => $this->repository->id), 'default') ?>">
        Remove this repository
        </a>
    </li>
</ul>
