<h2><?php echo $this->translate("Repositories") ?></h2>

<div class="ld-panel">

<?php $this->partialNavigationMenu('Ressources') ?>

<div class="ld-panel-content h6e-block">

<h3><?php echo $this->translate("Local repository") ?></h3>

<p><strong><?php echo $this->translate("Repository URL:") ?></strong> <?php echo $this->repository->getUrl() ?></p>

<?php require('repository.phtml') ?>

<hr/>

<h3><?php echo $this->translate("Upload a new package") ?></h3>

<p><?php echo $this->translate("Zip file please.") ?></p>

<form method="post" enctype="multipart/form-data" action="">
    <p>
        <input type="file" name="file"/>
        <input name="upload" class="submit" type="submit" value="<?php echo $this->translate("Upload") ?>"/>
    </p>
</form>

<hr/>

<h3><?php echo $this->translate("You can:") ?></h3>

<ul>
    <li>
        <a href="<?php echo $this->url(array('action' => 'delete', 'id' => $this->repository->id)) ?>">
        <?php echo $this->translate("Remove this repository") ?>
        </a>
    </li>
</ul>

</div>

</div>
