<h2><?php echo $this->translate("Browse repository") ?></h2>

<p><strong><?php echo $this->translate("Repository URL:") ?></strong> <?php echo $this->repository->getUrl() ?></p>

<?php require('repository.phtml') ?>

<h3>Actions</h3>

<ul>
    <li>
        <a href="<?php echo $this->url(array('action' => 'delete', 'id' => $this->repository->id)) ?>">
        <?php echo $this->translate("Remove this repository") ?>
        </a>
    </li>
</ul>
