<h2><?php echo $this->translate("Settings") ?></h2>

<div class="ld-panel">

<?php $this->partialNavigationMenu('Settings') ?>

<div class="ld-panel-content h6e-block">

<h3><?php echo $this->translate("Remote repository") ?></h3>

<p><strong><?php echo $this->translate("Repository URL:") ?></strong> <?php echo $this->repository->getUrl() ?></p>

<?php require('repository.phtml') ?>

<h3><?php echo $this->translate("You can:") ?></h3>

<ul>
    <li>
        <a href="<?php echo $this->url(array('action' => 'delete', 'id' => $this->repository->id)) ?>">
        <?php echo $this->translate("Remove this repository") ?>
        </a>
    </li>
</ul>

</div>

</div>
