<h2>Create new package</h2>

<form method="post" action="">

    <table>
        <tr>
            <td><label>Package Name</label></td>
            <td><input type="text" name="name" class="text" value=""/></td>
        </tr>
        <?php if ($this->type == 'library') : ?>
            <tr>
                <td><label>Library Type</label></td>
                <td>
                    <select name="type">
                        <option value="shared">Mixed (shared)</option>
                        <option value="lib">PHP (lib)</option>
                        <option value="css">CSS</option>
                        <option value="js">JS</option>
                    </select>
                </td>
            </tr>
        <?php endif ?>
    </table>
    
    <?php if ($this->type == 'application') : ?>
        <input type="hidden" name="type" value="application"/>
    <?php endif ?>
    
    <input type="submit" class="submit" value="Add"/>

</form>