<h2><?php echo $this->translate("Repositories") ?></h2>

<div class="ld-panel">

<?php $this->partialNavigationMenu('Ressources') ?>

<div class="ld-panel-content">

<h3><?php echo $this->translate("Add a new repository") ?></h3>

<form method="post" action="">
    
    <table class="ld-form">
    <?php if ($this->type == 'local') : ?>
    <tr>
        <th><label for="ld-repository-add-name"><?php echo $this->translate("Name") ?></label></th>
        <td><input id="ld-repository-add-name" type="text" name="name" class="text" value=""/></td>
    </tr>
    <?php elseif ($this->type == 'remote') : ?>
        <tr>
            <th><label for="ld-repository-add-url"><?php echo $this->translate("URL") ?></label></th>
            <td><input id="ld-repository-add-url" type="text" name="endpoint" class="text" value="" size="50"/></td>
        </tr>
    <?php endif ?>
    </table>
    
    <input type="hidden" name="type" value="<?php echo $this->type ?>" />
    <input type="submit" class="submit button ld-button" value="<?php echo $this->translate("Add") ?>"/>

</form>

</div>

</div>
