<?php if (empty($this->applications) && empty($this->libraries) && empty($this->extensions)) : ?>

    <p><?php echo $this->translate("This repository is empty.") ?></p>

<?php else : ?>

<table class="h6e-data">
    <?php foreach(array('applications', 'libraries', 'extensions') as $type) : ?>
        <?php if (!empty($this->$type)) : ?>
            <tr>
                <th colspan="4"><strong><?php echo $this->translate(ucfirst($type)) ?></strong></th>
            </tr>
            <tr class="th2">
                <th><?php echo $this->translate("Name") ?></th>
                <th><?php echo $this->translate("Package") ?></th>
                <th><?php echo $this->translate("Version") ?></th>
                <?php if ($this->repository->type == 'local') : ?>
                    <th><?php echo $this->translate("Actions") ?></th>
                <?php endif ?>
            </tr>
            <tbody>
            <?php foreach ($this->$type as $package) : ?>
                <tr>
                    <td><?php echo $package->name ?></td>
                    <td><?php echo $package->id ?></td>
                    <td><?php echo $package->version ?></td>
                    <?php if ($this->repository->type == 'local') : ?>
                        <?php
                        $removeUrl = $this->url(array('delete' => $package->id));
                        ?>
                        <td><a href="<?php echo $removeUrl ?>"><?php echo $this->translate("remove") ?></a></td>
                    <?php endif ?>
                </tr>
            <?php endforeach ?>
            </tbody>
        <?php endif ?>
    <?php endforeach ?>
</table>

<?php endif ?>