<?php if (empty($this->applications) &&  empty($this->libraries) && empty($this->extensions)) : ?>

    <p><?php echo $this->translate("This repository is empty.") ?></p>

<?php else : ?>

<table class="h6e-data">
    <?php foreach(array('applications', 'libraries', 'extensions') as $type) : ?>
        <?php if (!empty($this->$type)) : ?>
            <tr>
                <th colspan="3"><strong><?php echo $this->translate(ucfirst($type)) ?></strong></th>
            </tr>
            <tr class="th2">
                <th><?php echo $this->translate("Name") ?></th>
                <th><?php echo $this->translate("Package") ?></th>
                <th><?php echo $this->translate("Version") ?></th>
            </tr>
            <tbody>
            <?php foreach ($this->$type as $package) : ?>
                <tr>
                    <td><?php echo $package->name ?></td>
                    <td><?php echo $package->id ?></td>
                    <td><?php echo $package->version ?></td>
                </tr>
            <?php endforeach ?>
            </tbody>
        <?php endif ?>
    <?php endforeach ?>
</table>

<?php endif ?>