<h2><?php echo $this->translate("Sites") ?></h2>

<div class="ld-panel">

<div class="ld-panel-content h6e-block no-tab">

<h3><?php echo $this->translate("Create a new site") ?></h3>

<form method="post" action="">
  
    <?php $this->preferencesRenderer($this->preferences); ?>

    <input type="submit" class="submit button" value="<?php echo $this->translate("Create") ?>"/>

</form>

</div>

</div>